(function(root,factory){
  var node=typeof module==='object'&&module.exports;
  var api=factory(node?require('./colour-codec'):root.AXMColourCodec,node?require('fs'):null,node?require('path'):null,node?require('crypto'):null);
  if(node)module.exports=api;if(root)root.AXMPdfXCodec=api;
}(typeof globalThis!=='undefined'?globalThis:this,function(Colour,fs,path,crypto){
  'use strict';
  if(!Colour)throw new Error('AXM colour codec is required');
  var VERSION='1.0.0',PROFILE_PATH='/shared/asset-hands/vendor/icc/chemical-proof-cmyk.icc',PROFILE_SHA256='156e7c14f244cfc4ed83a755ca4803d80e15dd249b40fae82cb127d3902e15c7',PROFILE_BYTES=961644,profilePromise=null;
  function ascii(value){var out=new Uint8Array(value.length);for(var i=0;i<value.length;i+=1)out[i]=value.charCodeAt(i)&255;return out;}
  function text(bytes){var out='',step=32768;for(var i=0;i<bytes.length;i+=step)out+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(bytes.length,i+step)));return out;}
  function concat(parts){var size=parts.reduce(function(sum,item){return sum+item.length;},0),out=new Uint8Array(size),offset=0;parts.forEach(function(item){out.set(item,offset);offset+=item.length;});return out;}
  function base64(bytes){if(typeof Buffer!=='undefined')return Buffer.from(bytes).toString('base64');var binary='',step=32768;for(var i=0;i<bytes.length;i+=step)binary+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(bytes.length,i+step)));return btoa(binary);}
  function bytesFromDataUrl(value){var prefix='data:application/pdf;base64,';if(typeof value!=='string'||value.slice(0,prefix.length).toLowerCase()!==prefix)throw new Error('expected a base64 application/pdf data URL');var encoded=value.slice(prefix.length);if(typeof Buffer!=='undefined')return new Uint8Array(Buffer.from(encoded,'base64'));var binary=atob(encoded),out=new Uint8Array(binary.length);for(var i=0;i<binary.length;i+=1)out[i]=binary.charCodeAt(i);return out;}
  function pdfString(value){return'('+String(value==null?'':value).replace(/[\\()\r\n]/g,function(character){return{'\\':'\\\\','(':'\\(',')':'\\)','\r':' ','\n':' '}[character];}).slice(0,500)+')';}
  function xml(value){return String(value==null?'':value).replace(/[&<>"']/g,function(character){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[character];});}
  function number(value,min,max,name,fallback){var parsed=Number(value);if(!Number.isFinite(parsed))parsed=fallback;if(!Number.isFinite(parsed)||parsed<min||parsed>max)throw new Error(name+' must be between '+min+' and '+max);return parsed;}
  function fnv(value){var source=String(value),out=[];for(var seed=0;seed<4;seed+=1){var hash=(2166136261^seed)>>>0;for(var i=0;i<source.length;i+=1){hash^=source.charCodeAt(i);hash=Math.imul(hash,16777619);}out.push((hash>>>0).toString(16).padStart(8,'0'));}return out.join('').toUpperCase();}
  async function sha256(bytes){if(crypto)return crypto.createHash('sha256').update(Buffer.from(bytes)).digest('hex');if(globalThis.crypto&&globalThis.crypto.subtle){var digest=await globalThis.crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(function(value){return value.toString(16).padStart(2,'0');}).join('');}throw new Error('SHA-256 runtime unavailable');}
  async function loadProfile(){
    if(!profilePromise)profilePromise=(async function(){var bytes;if(fs&&path)bytes=new Uint8Array(fs.readFileSync(path.join(__dirname,'vendor','icc','chemical-proof-cmyk.icc')));else{var response=await fetch(PROFILE_PATH,{credentials:'same-origin'});if(!response.ok)throw new Error('CMYK profile fetch failed '+response.status);bytes=new Uint8Array(await response.arrayBuffer());}var hash=await sha256(bytes),inspection=Colour.parseIcc(bytes);if(bytes.length!==PROFILE_BYTES||hash!==PROFILE_SHA256)throw new Error('CMYK profile identity mismatch');if(!inspection.pass||inspection.deviceClass!=='prtr'||inspection.colourSpace!=='CMYK'||inspection.description!=='Chemical proof')throw new Error('CMYK profile structure or identity invalid');return{bytes:bytes,sha256:hash,inspection:inspection,name:'Chemical proof',copyright:'Created by Graeme W. Gill. Released into the public domain. No Warranty, Use at your own risk.'};}());
    var item=await profilePromise;return{bytes:new Uint8Array(item.bytes),sha256:item.sha256,inspection:JSON.parse(JSON.stringify(item.inspection)),name:item.name,copyright:item.copyright};
  }
  function streamObject(number,dict,bytes){return concat([ascii(number+' 0 obj\n<< '+dict+' /Length '+bytes.length+' >>\nstream\n'),bytes,ascii('\nendstream\nendobj\n')]);}
  function plainObject(number,body){return ascii(number+' 0 obj\n'+body+'\nendobj\n');}
  function xmpMetadata(title,condition){return'<?xpacket begin="\uFEFF" id="W5M0MpCehiHzreSzNTczkc9d"?>\n<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="AXM PDF/X codec '+VERSION+'"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/" xmlns:pdfxid="http://www.npes.org/pdfx/ns/id/" xmlns:dc="http://purl.org/dc/elements/1.1/"><pdf:Producer>AXM PDF/X Codec</pdf:Producer><pdfxid:GTS_PDFXVersion>PDF/X-4</pdfxid:GTS_PDFXVersion><dc:title><rdf:Alt><rdf:li xml:lang="x-default">'+xml(title)+'</rdf:li></rdf:Alt></dc:title><dc:description><rdf:Alt><rdf:li xml:lang="x-default">'+xml(condition)+'</rdf:li></rdf:Alt></dc:description></rdf:Description></rdf:RDF></x:xmpmeta>\n<?xpacket end="w"?>';}
  function contentStream(width,height,bleed,minimumStroke,cropMarks,registrationMarks){
    var mm=72/25.4,pageWidth=(width+2*bleed)*mm,pageHeight=(height+2*bleed)*mm,trimX=bleed*mm,trimY=bleed*mm,trimW=width*mm,trimH=height*mm,stroke=Math.max(.05,minimumStroke)*mm,parts=['q','0.82 0.24 0 0.08 k','0 0 '+pageWidth.toFixed(4)+' '+pageHeight.toFixed(4)+' re f','0.12 0.03 0 0.88 k',trimX.toFixed(4)+' '+trimY.toFixed(4)+' '+trimW.toFixed(4)+' '+trimH.toFixed(4)+' re f','0.72 0.08 0 0.05 K',stroke.toFixed(4)+' w',(trimX+trimW*.08).toFixed(4)+' '+(trimY+trimH*.28).toFixed(4)+' m '+(trimX+trimW*.92).toFixed(4)+' '+(trimY+trimH*.28).toFixed(4)+' l S','0.00 0.68 0.12 0.02 k',(trimX+trimW*.62).toFixed(4)+' '+(trimY+trimH*.58).toFixed(4)+' '+(trimW*.23).toFixed(4)+' '+(trimH*.20).toFixed(4)+' re f'];
    if(bleed>0&&cropMarks){var mark=Math.min(5,Math.max(2,bleed*.8))*mm,gap=.4*mm,x0=trimX,y0=trimY,x1=trimX+trimW,y1=trimY+trimH;parts.push('0 0 0 1 K',Math.max(.1*mm,stroke*.5).toFixed(4)+' w',[x0-mark,y0,x0-gap,y0,x0,y0-mark,x0,y0-gap,x1+gap,y0,x1+mark,y0,x1,y0-mark,x1,y0-gap,x0-mark,y1,x0-gap,y1,x0,y1+gap,x0,y1+mark,x1+gap,y1,x1+mark,y1,x1,y1+gap,x1,y1+mark].reduce(function(lines,value,index,array){if(index%4===0)lines.push(array[index].toFixed(4)+' '+array[index+1].toFixed(4)+' m '+array[index+2].toFixed(4)+' '+array[index+3].toFixed(4)+' l S');return lines;},[]).join('\n'));}
    if(registrationMarks&&bleed>2){var cx=pageWidth/2,cy=pageHeight/2,r=Math.min(bleed*mm*.25,2*mm);parts.push('1 0 0 0 K',Math.max(.1*mm,stroke*.5).toFixed(4)+' w',(cx-r).toFixed(4)+' '+(trimY/2).toFixed(4)+' m '+(cx+r).toFixed(4)+' '+(trimY/2).toFixed(4)+' l S',cx.toFixed(4)+' '+(trimY/2-r).toFixed(4)+' m '+cx.toFixed(4)+' '+(trimY/2+r).toFixed(4)+' l S');}
    parts.push('Q');return ascii(parts.join('\n')+'\n');
  }
  function buildPdf(objects,id){var header=ascii('%PDF-1.6\n%\xE2\xE3\xCF\xD3\n'),parts=[header],offsets=[0],offset=header.length;for(var i=1;i<objects.length;i+=1){offsets[i]=offset;parts.push(objects[i]);offset+=objects[i].length;}var xrefOffset=offset,xref='xref\n0 '+objects.length+'\n0000000000 65535 f \n';for(var n=1;n<objects.length;n+=1)xref+=String(offsets[n]).padStart(10,'0')+' 00000 n \n';var tail=ascii(xref+'trailer\n<< /Size '+objects.length+' /Root 1 0 R /Info 9 0 R /ID [<'+id+'><'+id+'>] >>\nstartxref\n'+xrefOffset+'\n%%EOF\n');parts.push(tail);return concat(parts);}
  function parseXref(bytes,source,errors){var marker=source.lastIndexOf('startxref\n'),offsets=[];if(marker<0){errors.push('startxref missing');return offsets;}var xrefOffset=Number(/^([0-9]+)/.exec(source.slice(marker+10))&&RegExp.$1);if(!Number.isInteger(xrefOffset)||source.slice(xrefOffset,xrefOffset+5)!=='xref\n'){errors.push('startxref does not point to xref');return offsets;}var lines=source.slice(xrefOffset).split('\n'),header=/^0 ([0-9]+)$/.exec(lines[1]||'');if(!header){errors.push('xref subsection header invalid');return offsets;}for(var i=1;i<Number(header[1]);i+=1){var match=/^([0-9]{10}) 00000 n /.exec(lines[i+2]||'');if(!match){errors.push('xref entry '+i+' invalid');continue;}offsets[i]=Number(match[1]);if(source.slice(offsets[i],offsets[i]+String(i).length+6)!==i+' 0 obj')errors.push('xref entry '+i+' points to the wrong object');}return offsets;}
  function objectStream(bytes,source,offsets,number,errors){var offset=offsets[number];if(offset==null){errors.push('object '+number+' missing');return null;}var headerEnd=source.indexOf('stream\n',offset),objectEnd=source.indexOf('endobj',offset);if(headerEnd<0||objectEnd<0||headerEnd>objectEnd){errors.push('object '+number+' stream missing');return null;}var header=source.slice(offset,headerEnd),lengthMatch=/\/Length\s+([0-9]+)/.exec(header);if(!lengthMatch){errors.push('object '+number+' stream length missing');return null;}var start=headerEnd+7,length=Number(lengthMatch[1]);if(start+length>bytes.length){errors.push('object '+number+' stream exceeds file');return null;}return bytes.subarray(start,start+length);}
  function inspect(bytes,expected){
    expected=expected||{};var source=text(bytes),errors=[],warnings=[];
    if(source.slice(0,8)!=='%PDF-1.6')errors.push('PDF 1.6 header missing');if(!/%%EOF\s*$/.test(source))errors.push('PDF EOF marker missing');
    var offsets=parseXref(bytes,source,errors),intent=/\/OutputIntents\s*\[\s*([0-9]+)\s+0\s+R\s*\]/.exec(source),profileRef=/\/DestOutputProfile\s+([0-9]+)\s+0\s+R/.exec(source),profileBytes=profileRef?objectStream(bytes,source,offsets,Number(profileRef[1]),errors):null,icc=profileBytes?Colour.parseIcc(profileBytes):null;
    if(!intent)errors.push('catalog OutputIntents missing');if(!/\/S\s*\/GTS_PDFX/.test(source))errors.push('GTS_PDFX output intent subtype missing');if(!profileRef)errors.push('DestOutputProfile missing');
    if(!icc||!icc.pass)errors.push('embedded CMYK ICC profile invalid');else{if(icc.deviceClass!=='prtr')errors.push('output intent ICC class is not printer');if(icc.colourSpace!=='CMYK')errors.push('output intent ICC colour space is not CMYK');if(icc.description!=='Chemical proof')errors.push('unexpected CMYK profile identity');}
    if(profileBytes&&expected.profileBytes instanceof Uint8Array){if(profileBytes.length!==expected.profileBytes.length)errors.push('embedded CMYK profile byte length differs from installed profile');else for(var profileIndex=0;profileIndex<profileBytes.length;profileIndex+=1)if(profileBytes[profileIndex]!==expected.profileBytes[profileIndex]){errors.push('embedded CMYK profile differs from installed profile');break;}}
    if(source.indexOf('<pdfxid:GTS_PDFXVersion>PDF/X-4</pdfxid:GTS_PDFXVersion>')<0)errors.push('PDF/X-4 XMP identifier missing');
    if(source.indexOf('/GTS_PDFXVersion (PDF/X-4)')<0)errors.push('PDF/X-4 Info identifier missing');
    if(!/\/MediaBox\s*\[[^\]]+\]/.test(source)||!/\/TrimBox\s*\[[^\]]+\]/.test(source)||!/\/BleedBox\s*\[[^\]]+\]/.test(source))errors.push('required page boxes missing');
    if(!/(?:^|\s)[0-9.]+\s+[0-9.]+\s+[0-9.]+\s+[0-9.]+\s+[kK](?:\s|$)/m.test(source))errors.push('DeviceCMYK paint operators missing');
    if(/\/Font\b/.test(source))errors.push('bounded vector PDF/X profile forbids unembedded fonts');if(/\/JavaScript\b|\/Launch\b|\/URI\b/.test(source))errors.push('active or external PDF actions are forbidden');
    if(expected.widthPt&&source.indexOf(expected.widthPt.toFixed(4))<0)errors.push('expected page width not found');if(expected.heightPt&&source.indexOf(expected.heightPt.toFixed(4))<0)errors.push('expected page height not found');
    return{pass:!errors.length,errors:errors,warnings:warnings,bytes:bytes.length,header:source.slice(0,8),xrefObjects:offsets.filter(function(value){return value!=null;}).length,outputIntent:!!intent,pdfXVersion:'PDF/X-4',deviceCmyk:/[0-9.]\s+[0-9.]\s+[0-9.]\s+[0-9.]\s+[kK]/.test(source),icc:icc?{pass:icc.pass,bytes:profileBytes.length,description:icc.description,deviceClass:icc.deviceClass,colourSpace:icc.colourSpace,pcs:icc.pcs}:null,noFonts:!(/\/Font\b/.test(source)),noActiveContent:!(/\/JavaScript\b|\/Launch\b|\/URI\b/.test(source))};
  }
  async function encode(input){
    input=input||{};var width=number(input.widthMm,10,2000,'print width',210),height=number(input.heightMm,10,2000,'print height',297),bleed=number(input.bleedMm,0,50,'bleed',3),minimumStroke=number(input.minimumStrokeMm,.05,20,'minimum stroke',.25),condition=String(input.outputCondition||'Chemical proof').trim();
    if(!/^(?:chemical proof|generic[- ]cmyk)$/i.test(condition))throw new Error('installed PDF/X hand supports only the exact Chemical proof CMYK output condition');
    var profile=await loadProfile(),mm=72/25.4,pageWidth=(width+2*bleed)*mm,pageHeight=(height+2*bleed)*mm,trim=[bleed*mm,bleed*mm,(bleed+width)*mm,(bleed+height)*mm],content=contentStream(width,height,bleed,minimumStroke,input.cropMarks!==false,input.registrationMarks===true),xmp=ascii(xmpMetadata(input.title||'AXM PDF/X document','Chemical proof CMYK output condition')),
      objects=[null];
    objects[1]=plainObject(1,'<< /Type /Catalog /Pages 2 0 R /OutputIntents [7 0 R] /Metadata 8 0 R >>');
    objects[2]=plainObject(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
    objects[3]=plainObject(3,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '+pageWidth.toFixed(4)+' '+pageHeight.toFixed(4)+'] /TrimBox ['+trim.map(function(value){return value.toFixed(4);}).join(' ')+'] /BleedBox [0 0 '+pageWidth.toFixed(4)+' '+pageHeight.toFixed(4)+'] /Resources << >> /Contents 4 0 R >>');
    objects[4]=streamObject(4,'',content);
    objects[5]=plainObject(5,'<< >>');
    objects[6]=streamObject(6,'/N 4 /Alternate /DeviceCMYK',profile.bytes);
    objects[7]=plainObject(7,'<< /Type /OutputIntent /S /GTS_PDFX /OutputConditionIdentifier '+pdfString('Chemical proof')+' /OutputCondition '+pdfString('Generic chemical proof CMYK condition')+' /RegistryName '+pdfString('http://www.color.org')+' /Info '+pdfString('Chemical proof CMYK')+' /DestOutputProfile 6 0 R >>');
    objects[8]=streamObject(8,'/Type /Metadata /Subtype /XML',xmp);
    objects[9]=plainObject(9,'<< /Title '+pdfString(input.title||'AXM PDF/X document')+' /Creator '+pdfString('AXM PDF/X Production Hand')+' /Producer '+pdfString('AXM PDF/X Codec '+VERSION)+' /CreationDate (D:20000101000000Z) /ModDate (D:20000101000000Z) /GTS_PDFXVersion (PDF/X-4) /Trapped /False >>');
    var id=fnv([input.title,width,height,bleed,minimumStroke,input.cropMarks,input.registrationMarks,profile.sha256].join('|')),bytes=buildPdf(objects,id),inspection=inspect(bytes,{widthPt:pageWidth,heightPt:pageHeight});if(!inspection.pass)throw new Error('PDF/X structural validation failed: '+inspection.errors.join(', '));
    return{mime:'application/pdf',format:'PDF/X-4',widthMm:width,heightMm:height,bleedMm:bleed,pageWidthMm:width+2*bleed,pageHeightMm:height+2*bleed,minimumStrokeMm:minimumStroke,byteLength:bytes.length,bytes:bytes,dataUrl:'data:application/pdf;base64,'+base64(bytes),profile:profile,inspection:inspection,outputCondition:'Chemical proof',conformance:'AXM bounded vector PDF/X-4 profile'};
  }
  return{VERSION:VERSION,PROFILE_PATH:PROFILE_PATH,PROFILE_SHA256:PROFILE_SHA256,loadProfile:loadProfile,encode:encode,inspect:inspect,bytesFromDataUrl:bytesFromDataUrl};
}));
