(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.AXMToolpathCodec=api;}(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  var VERSION='1.0.0',UNIT_CODES={4:'mm',6:'m'};
  function number(value,label){var parsed=Number(value);if(!Number.isFinite(parsed))throw new Error(label+' is not numeric');return parsed;}
  function group(entity,code,fallback){var found=entity.find(function(item){return item.code===code;});return found?found.value:fallback;}
  function parseDxf(source){
    if(typeof source!=='string'||source.length<20||source.length>8000000)throw new Error('DXF source must be bounded ASCII text');var lines=source.replace(/\r/g,'').split('\n'),pairs=[];for(var i=0;i+1<lines.length;i+=2){var code=Number(lines[i].trim());if(!Number.isInteger(code))throw new Error('DXF group code is invalid at line '+(i+1));pairs.push({code:code,value:lines[i+1].trim()});}
    if(!pairs.some(function(item,index){return item.code===0&&item.value==='EOF'&&index===pairs.length-1;}))throw new Error('DXF EOF marker missing');var unitCode=null;for(var header=0;header<pairs.length-1;header+=1)if(pairs[header].code===9&&pairs[header].value==='$INSUNITS'){var next=pairs.slice(header+1).find(function(item){return item.code===70;});unitCode=next?Number(next.value):null;break;}var unit=UNIT_CODES[unitCode];if(!unit)throw new Error('DXF $INSUNITS must declare millimetres or metres');var entities=[];
    for(var at=0;at<pairs.length;at+=1){if(pairs[at].code!==0||['LINE','LWPOLYLINE','CIRCLE'].indexOf(pairs[at].value)<0)continue;var type=pairs[at].value,body=[];for(at+=1;at<pairs.length&&pairs[at].code!==0;at+=1)body.push(pairs[at]);at-=1;var layer=String(group(body,8,'0')).slice(0,80),points=[],closed=false;
      if(type==='LINE')points=[[number(group(body,10),'LINE x1'),number(group(body,20),'LINE y1')],[number(group(body,11),'LINE x2'),number(group(body,21),'LINE y2')]];
      else if(type==='CIRCLE'){var cx=number(group(body,10),'CIRCLE cx'),cy=number(group(body,20),'CIRCLE cy'),radius=number(group(body,40),'CIRCLE radius');if(!(radius>0))throw new Error('CIRCLE radius must be positive');for(var step=0;step<64;step+=1){var angle=step*Math.PI*2/64;points.push([cx+Math.cos(angle)*radius,cy+Math.sin(angle)*radius]);}closed=true;}
      else{var current=null;body.forEach(function(item){if(item.code===10){current=[number(item.value,'polyline x'),null];points.push(current);}else if(item.code===20&&current&&current[1]==null)current[1]=number(item.value,'polyline y');});if(points.some(function(point){return point[1]==null;}))throw new Error('LWPOLYLINE vertex is missing y');closed=(Number(group(body,70,0))&1)===1;}
      if(points.length<2)throw new Error(type+' contains too few points');entities.push({type:type,layer:layer,points:points,closed:closed});
    }
    if(!entities.length)throw new Error('DXF contains no supported LINE, LWPOLYLINE or CIRCLE entities');return{unit:unit,unitCode:unitCode,entities:entities,entityCount:entities.length,sourceBytes:source.length};
  }
  function scalePlan(parsed,targetUnit){var factor=parsed.unit===targetUnit?1:parsed.unit==='m'&&targetUnit==='mm'?1000:parsed.unit==='mm'&&targetUnit==='m'?.001:null;if(factor==null)throw new Error('DXF unit cannot be transformed to target unit');return{unit:targetUnit,entities:parsed.entities.map(function(entity){return{type:entity.type,layer:entity.layer,closed:entity.closed,points:entity.points.map(function(point){return[point[0]*factor,point[1]*factor];})};}),unitTransform:factor};}
  function distance(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1]);}
  function operation(layer,requested){var signal=String(layer).toLowerCase();if(/engrave|etch|mark|slot/.test(signal))return'engrave';if(/cut|profile|outline/.test(signal))return'cut';var list=(requested||[]).map(function(value){return String(value).toLowerCase();});return list.indexOf('engrave')>=0&&list.indexOf('cut')<0?'engrave':'cut';}
  function simulate(parsed,options){
    options=options||{};var plan=scalePlan(parsed,options.unit),width=Number(options.width),height=Number(options.height),tool=Number(options.toolWidth),depth=Number(options.depth)||0,thickness=options.materialThickness==null?null:Number(options.materialThickness),tolerance=Number(options.tolerance)||0,kerfSide=String(options.kerfSide||'centerline'),radius=tool/2+tolerance,errors=[],warnings=[],paths=[],cutLength=0,rapidLength=0,previous=null,min=[Infinity,Infinity],max=[-Infinity,-Infinity],requested=options.operations||[],feed=Number(options.feedRate)||300,passDepth=Math.max(options.unit==='m'?.0001:.1,Math.min(tool/2||1,options.unit==='m'?.005:5)),passes=depth>0?Math.ceil(depth/passDepth):1;
    if(!(width>0&&height>0&&tool>0))errors.push('stock dimensions and tool width must be positive');if(depth<0)errors.push('depth cannot be negative');if(thickness!=null&&depth>thickness+tolerance)errors.push('requested depth exceeds material thickness plus tolerance');if(['inside','outside','centerline'].indexOf(kerfSide)<0)errors.push('kerf side is unsupported');
    plan.entities.forEach(function(entity,index){var op=operation(entity.layer,requested),points=entity.points,segments=entity.closed?points.length:points.length-1,length=0;for(var i=0;i<segments;i+=1)length+=distance(points[i],points[(i+1)%points.length]);if(previous)rapidLength+=distance(previous,points[0]);previous=entity.closed?points[0]:points[points.length-1];points.forEach(function(point){min[0]=Math.min(min[0],point[0]-radius);min[1]=Math.min(min[1],point[1]-radius);max[0]=Math.max(max[0],point[0]+radius);max[1]=Math.max(max[1],point[1]+radius);});if(op==='cut'&&!entity.closed)warnings.push('CUT path '+index+' on layer '+entity.layer+' is open');cutLength+=length*passes;paths.push({index:index,source_type:entity.type,layer:entity.layer,operation:op,closed:entity.closed,points:points,length:length,passes:passes,depth:depth,kerf_side:kerfSide,swept_radius:radius});});
    var requestedOps=requested.map(function(value){return String(value).toLowerCase();}).filter(function(value){return value==='cut'||value==='engrave';}),operationsPass=!requestedOps.length||paths.every(function(path){return requestedOps.indexOf(path.operation)>=0;});if(!operationsPass)errors.push('DXF layers contain operations outside the target canvas contract');if(min[0]<-tolerance||min[1]<-tolerance||max[0]>width+tolerance||max[1]>height+tolerance)errors.push('swept tool envelope leaves stock bounds');var estimatedMinutes=cutLength/Math.max(.001,feed)+rapidLength/Math.max(.001,feed*3),checks=[{name:'supported-dxf-entities',pass:paths.length>0},{name:'requested-operations-only',pass:operationsPass,details:{requested:requestedOps,actual:paths.map(function(path){return path.operation;})}},{name:'swept-envelope-inside-stock',pass:!(min[0]<-tolerance||min[1]<-tolerance||max[0]>width+tolerance||max[1]>height+tolerance),details:{minimum:min,maximum:max,stock:[width,height]}},{name:'depth-within-material',pass:thickness==null||depth<=thickness+tolerance,details:{depth:depth,thickness:thickness,tolerance:tolerance}},{name:'finite-path-length',pass:Number.isFinite(cutLength)&&cutLength>0},{name:'bounded-pass-plan',pass:passes>=1&&passes<=1000,details:{passes:passes,max_pass_depth:passDepth}}];if(passes>1000)errors.push('depth plan exceeds 1000 passes');return{schema:'axm.toolpath-simulation/v1',version:'1.0.0',status:errors.length?'HOLD':'PASS',unit:options.unit,stock:{width:width,height:height,material_thickness:thickness},tool:{width:tool,swept_radius:radius,kerf_side:kerfSide},depth:{requested:depth,max_per_pass:passDepth,passes:passes},feeds:{cut_per_minute:feed,rapid_per_minute:feed*3},bounds:{minimum:min,maximum:max},paths:paths,cut_length:cutLength,rapid_length:rapidLength,estimated_minutes:estimatedMinutes,errors:errors,warnings:warnings,checks:checks,automatic_execution:false};
  }
  function approval(value,sourceDigest){var errors=[];if(!value||value.schema!=='axm.machine-export-approval/v1')errors.push('machine export approval schema missing');if(!value||value.approved!==true)errors.push('machine export is not approved');if(!value||value.authority!=='human-operator')errors.push('approval authority must be human-operator');if(!value||value.source_digest!==sourceDigest)errors.push('approval source digest does not match DXF');var profile=value&&value.machine_profile;if(!profile||typeof profile.id!=='string'||!profile.id)errors.push('approved machine profile id missing');if(!profile||profile.units!=='mm')errors.push('approved machine profile must explicitly use mm');if(!profile||!Number.isFinite(Number(profile.safe_z))||Number(profile.safe_z)<=0)errors.push('approved machine safe_z must be positive');if(!profile||!Array.isArray(profile.work_area_mm)||profile.work_area_mm.length!==2||profile.work_area_mm.some(function(item){return!(Number(item)>0);}))errors.push('approved machine work_area_mm must contain two positive dimensions');return{pass:!errors.length,errors:errors,profile:profile||null,approved_at:value&&value.approved_at||null};}
  function gcode(simulation,approvalReceipt){if(simulation.status!=='PASS')throw new Error('machine code cannot be prepared from a held simulation');if(!approvalReceipt||!approvalReceipt.pass)throw new Error('OPERATOR_APPROVAL_REQUIRED: '+((approvalReceipt&&approvalReceipt.errors)||[]).join(', '));var profile=approvalReceipt.profile,safeZ=Number(profile.safe_z),unit=simulation.unit,scale=unit==='m'?1000:1;if(simulation.stock.width*scale>Number(profile.work_area_mm[0])||simulation.stock.height*scale>Number(profile.work_area_mm[1]))throw new Error('approved machine work area is smaller than the target stock');var lines=['(AXM candidate machine code - operator review still required)','(machine profile '+String(profile.id).replace(/[()\r\n]/g,' ')+')','G21','G90','G17','M5','G0 Z'+safeZ.toFixed(3)];simulation.paths.forEach(function(path){for(var pass=1;pass<=path.passes;pass+=1){var z=-Math.min(path.depth,path.depth*pass/path.passes)*scale,first=path.points[0];lines.push('(path '+path.index+' '+path.operation+' pass '+pass+'/'+path.passes+')','G0 X'+(first[0]*scale).toFixed(3)+' Y'+(first[1]*scale).toFixed(3),'G1 Z'+z.toFixed(3)+' F'+Math.round(simulation.feeds.cut_per_minute*scale));for(var i=1;i<path.points.length;i+=1)lines.push('G1 X'+(path.points[i][0]*scale).toFixed(3)+' Y'+(path.points[i][1]*scale).toFixed(3));if(path.closed)lines.push('G1 X'+(first[0]*scale).toFixed(3)+' Y'+(first[1]*scale).toFixed(3));lines.push('G0 Z'+safeZ.toFixed(3));}});lines.push('M5','G0 X0 Y0','M30');var text=lines.join('\n')+'\n',inspection=inspectGcode(text);if(!inspection.pass)throw new Error('generated G-code safety validation failed: '+inspection.errors.join(', '));return{text:text,inspection:inspection,automaticExecution:false};}
  function inspectGcode(source){var errors=[],commands=[],allowed=['G0','G00','G1','G01','G17','G20','G21','G90','M5','M30'];String(source||'').split(/\r?\n/).forEach(function(line,index){var clean=line.replace(/\([^)]*\)/g,'').trim();if(!clean)return;var command=/^([GMT][0-9]+)/i.exec(clean);if(!command){errors.push('line '+(index+1)+' has no supported command');return;}var normalized=command[1].toUpperCase();commands.push(normalized);if(allowed.indexOf(normalized)<0)errors.push('line '+(index+1)+' command '+normalized+' is outside the safe subset');if(/\b(?:M3|M4|M6|G2|G3|G28|G53|G54|G92)\b/i.test(clean))errors.push('line '+(index+1)+' contains forbidden stateful command');});if(commands.indexOf('G21')<0)errors.push('millimetre mode G21 missing');if(commands.indexOf('G90')<0)errors.push('absolute mode G90 missing');if(commands[commands.length-1]!=='M30')errors.push('program end M30 missing');return{pass:!errors.length,errors:errors,commands:commands,lines:String(source||'').split(/\r?\n/).length};}
  return{VERSION:VERSION,parseDxf:parseDxf,simulate:simulate,approval:approval,gcode:gcode,inspectGcode:inspectGcode};
}));
