(function(root,factory){var node=typeof module==='object'&&module.exports,api=factory(node?require('./animated-web-codec'):root.AXMAnimatedWebCodec);if(node)module.exports=api;if(root)root.AXMVideoCodec=api;}(typeof globalThis!=='undefined'?globalThis:this,function(Animated){
  'use strict';if(!Animated)throw new Error('AXM animated-web codec is required');var VERSION='1.0.0';
  function asBytes(value){if(value instanceof Uint8Array)return value;if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);throw new Error('video bytes must be a typed array');}
  function concat(parts){var length=parts.reduce(function(sum,item){return sum+item.length;},0),out=new Uint8Array(length),offset=0;parts.forEach(function(item){out.set(item,offset);offset+=item.length;});return out;}
  function ascii(value){var out=new Uint8Array(value.length);for(var i=0;i<value.length;i+=1)out[i]=value.charCodeAt(i)&255;return out;}
  function text(bytes,offset,length){var out='';for(var i=0;i<length&&offset+i<bytes.length;i+=1)out+=String.fromCharCode(bytes[offset+i]);return out;}
  function zeros(length){return new Uint8Array(length);}
  function be16(value){return new Uint8Array([(value>>>8)&255,value&255]);}
  function be24(value){return new Uint8Array([(value>>>16)&255,(value>>>8)&255,value&255]);}
  function be32(value){return new Uint8Array([(value>>>24)&255,(value>>>16)&255,(value>>>8)&255,value&255]);}
  function read16(bytes,offset){return(bytes[offset]<<8)|bytes[offset+1];}
  function read32(bytes,offset){return((bytes[offset]<<24)|(bytes[offset+1]<<16)|(bytes[offset+2]<<8)|bytes[offset+3])>>>0;}
  function base64(bytes){if(typeof Buffer!=='undefined')return Buffer.from(bytes).toString('base64');var value='',step=32768;for(var i=0;i<bytes.length;i+=step)value+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(bytes.length,i+step)));return btoa(value);}
  function dataUrl(mime,bytes){return'data:'+mime+';base64,'+base64(bytes);}
  function bytesFromDataUrl(value,mime){var match=/^data:([^;,]+);base64,([a-z0-9+/=]+)$/i.exec(String(value||''));if(!match)throw new Error('video source requires a base64 data URL');if(mime&&match[1].toLowerCase()!==mime.toLowerCase())throw new Error('video source MIME mismatch');if(typeof Buffer!=='undefined')return new Uint8Array(Buffer.from(match[2],'base64'));var binary=atob(match[2]),out=new Uint8Array(binary.length);for(var i=0;i<binary.length;i+=1)out[i]=binary.charCodeAt(i);return out;}
  function box(type){var payload=concat(Array.prototype.slice.call(arguments,1)),size=8+payload.length;return concat([be32(size),ascii(type),payload]);}
  function full(version,flags,payload){return concat([new Uint8Array([version,(flags>>>16)&255,(flags>>>8)&255,flags&255]),payload||new Uint8Array(0)]);}
  function matrix(){return concat([be32(0x00010000),be32(0),be32(0),be32(0),be32(0x00010000),be32(0),be32(0),be32(0),be32(0x40000000)]);}
  function jpegEntry(width,height){var name=zeros(32),label='AXM Motion JPEG';name[0]=label.length;name.set(ascii(label),1);return box('jpeg',zeros(6),be16(1),zeros(16),be16(width),be16(height),be32(0x00480000),be32(0x00480000),be32(0),be16(1),name,be16(24),be16(0xffff));}
  function mp4(samples,width,height,fps){var timescale=1000,delta=Math.max(1,Math.round(timescale/fps)),duration=delta*samples.length,ftyp=box('ftyp',ascii('isom'),be32(0x200),ascii('isomiso2mp41')),mdatPayload=concat(samples),mdat=box('mdat',mdatPayload),chunkOffset=ftyp.length+8,mvhd=box('mvhd',full(0,0,concat([be32(0),be32(0),be32(timescale),be32(duration),be32(0x00010000),be16(0x0100),be16(0),zeros(8),matrix(),zeros(24),be32(2)]))),tkhd=box('tkhd',full(0,7,concat([be32(0),be32(0),be32(1),be32(0),be32(duration),zeros(8),be16(0),be16(0),be16(0),be16(0),matrix(),be32(width<<16),be32(height<<16)]))),mdhd=box('mdhd',full(0,0,concat([be32(0),be32(0),be32(timescale),be32(duration),be16(0x55c4),be16(0)]))),hdlr=box('hdlr',full(0,0,concat([be32(0),ascii('vide'),zeros(12),ascii('AXM Video\0')]))),vmhd=box('vmhd',full(0,1,concat([be16(0),be16(0),be16(0),be16(0)]))),url=box('url ',full(0,1,new Uint8Array(0))),dref=box('dref',full(0,0,concat([be32(1),url]))),dinf=box('dinf',dref),stsd=box('stsd',full(0,0,concat([be32(1),jpegEntry(width,height)]))),stts=box('stts',full(0,0,concat([be32(1),be32(samples.length),be32(delta)]))),stsc=box('stsc',full(0,0,concat([be32(1),be32(1),be32(samples.length),be32(1)]))),sizes=concat(samples.map(function(sample){return be32(sample.length);})),stsz=box('stsz',full(0,0,concat([be32(0),be32(samples.length),sizes]))),stco=box('stco',full(0,0,concat([be32(1),be32(chunkOffset)]))),sync=concat(samples.map(function(_,index){return be32(index+1);})),stss=box('stss',full(0,0,concat([be32(samples.length),sync]))),stbl=box('stbl',stsd,stts,stsc,stsz,stco,stss),minf=box('minf',vmhd,dinf,stbl),mdia=box('mdia',mdhd,hdlr,minf),trak=box('trak',tkhd,mdia),moov=box('moov',mvhd,trak),bytes=concat([ftyp,mdat,moov]),inspection=inspectMp4(bytes);if(!inspection.pass)throw new Error('MP4 validation failed: '+inspection.errors.join(', '));return{bytes:bytes,byteLength:bytes.length,dataUrl:dataUrl('video/mp4',bytes),inspection:inspection,codec:'jpeg',timescale:timescale,frameDelta:delta};}
  function mp4Boxes(bytes,start,end,errors,all){var containers=['moov','trak','mdia','minf','stbl','dinf'];for(var offset=start;offset+8<=end;){var size=read32(bytes,offset),type=text(bytes,offset+4,4);if(size<8||offset+size>end){errors.push(type+' MP4 box exceeds parent');break;}var item={type:type,start:offset,end:offset+size,size:size,payloadStart:offset+8};all.push(item);if(containers.indexOf(type)>=0)mp4Boxes(bytes,item.payloadStart,item.end,errors,all);offset+=size;}if(start<end&&!all.some(function(item){return item.start===start;})){/* parent may be empty */}}
  function inspectMp4(value){var bytes=asBytes(value),errors=[],all=[];mp4Boxes(bytes,0,bytes.length,errors,all);function one(type){return all.find(function(item){return item.type===type;});}var ftyp=one('ftyp'),mdat=one('mdat'),moov=one('moov'),stsd=one('stsd'),stts=one('stts'),stsz=one('stsz'),stco=one('stco'),mvhd=one('mvhd'),tkhd=one('tkhd'),samples=[],width=null,height=null,timescale=null,duration=null,delta=null;if(!ftyp||text(bytes,ftyp.payloadStart,4)!=='isom')errors.push('MP4 isom file type missing');if(!mdat)errors.push('MP4 mdat missing');if(!moov)errors.push('MP4 moov missing');if(!stsd||text(bytes,stsd.payloadStart,stsd.size-8).indexOf('jpeg')<0)errors.push('MP4 jpeg visual sample entry missing');if(stts&&stts.size>=24){var entries=read32(bytes,stts.payloadStart+4);if(entries!==1)errors.push('bounded MP4 requires one stts entry');var count=read32(bytes,stts.payloadStart+8);delta=read32(bytes,stts.payloadStart+12);samples.length=count;}else errors.push('MP4 stts invalid');if(mvhd&&mvhd.size>=32){timescale=read32(bytes,mvhd.payloadStart+12);duration=read32(bytes,mvhd.payloadStart+16);if(!timescale||duration!==samples.length*delta)errors.push('MP4 duration/timebase mismatch');}else errors.push('MP4 mvhd invalid');if(tkhd&&tkhd.size>=92){width=read32(bytes,tkhd.end-8)>>>16;height=read32(bytes,tkhd.end-4)>>>16;}else errors.push('MP4 tkhd invalid');if(stsz&&stsz.size>=20){var sampleSize=read32(bytes,stsz.payloadStart+4),sampleCount=read32(bytes,stsz.payloadStart+8);if(sampleSize!==0)errors.push('MP4 bounded profile requires explicit sample sizes');if(sampleCount!==samples.length)errors.push('MP4 sample count mismatch');samples=[];for(var i=0;i<sampleCount;i+=1)samples.push(read32(bytes,stsz.payloadStart+12+i*4));}else errors.push('MP4 stsz invalid');var chunkOffset=null;if(stco&&stco.size>=20){if(read32(bytes,stco.payloadStart+4)!==1)errors.push('MP4 bounded profile requires one chunk');chunkOffset=read32(bytes,stco.payloadStart+8);}else errors.push('MP4 stco invalid');if(mdat&&chunkOffset!==mdat.payloadStart)errors.push('MP4 chunk offset does not point to mdat payload');if(mdat&&samples.reduce(function(sum,size){return sum+size;},0)!==mdat.size-8)errors.push('MP4 sample sizes do not fill mdat');var cursor=chunkOffset||0;samples.forEach(function(size,index){if(size<4||cursor+size>bytes.length||bytes[cursor]!==0xff||bytes[cursor+1]!==0xd8||bytes[cursor+size-2]!==0xff||bytes[cursor+size-1]!==0xd9)errors.push('MP4 JPEG sample '+index+' markers invalid');cursor+=size;});return{pass:!errors.length,errors:errors,mime:'video/mp4',format:'MP4',codec:'jpeg',profile:'bounded Motion JPEG in ISO BMFF',bytes:bytes.length,width:width,height:height,frames:samples.length,timescale:timescale,frameDelta:delta,durationSeconds:timescale?duration/timescale:null,fps:delta?timescale/delta:null,sampleSizes:samples,chunkOffset:chunkOffset,mdat:{start:mdat&&mdat.payloadStart,length:mdat&&mdat.size-8},boxes:all.map(function(item){return item.type;})};}
  function hexId(value){var textValue=String(value).replace(/^0x/,'');if(textValue.length%2)textValue='0'+textValue;var out=new Uint8Array(textValue.length/2);for(var i=0;i<out.length;i+=1)out[i]=parseInt(textValue.slice(i*2,i*2+2),16);return out;}
  function vintSize(value){for(var length=1;length<=8;length+=1){var max=Math.pow(2,7*length)-2;if(value<=max){var out=new Uint8Array(length),rest=value;for(var index=length-1;index>=0;index-=1){out[index]=rest&255;rest=Math.floor(rest/256);}out[0]|=1<<(8-length);return out;}}throw new Error('EBML element is too large');}
  function uintBytes(value){value=Math.max(0,Math.floor(Number(value)||0));var length=value<=0xff?1:value<=0xffff?2:value<=0xffffff?3:4,out=new Uint8Array(length);for(var i=length-1;i>=0;i-=1){out[i]=value&255;value=Math.floor(value/256);}return out;}
  function float64(value){var out=new Uint8Array(8),view=new DataView(out.buffer);view.setFloat64(0,Number(value),false);return out;}
  function ebml(id,data){data=asBytes(data);return concat([hexId(id),vintSize(data.length),data]);}
  function master(id,children){return ebml(id,concat(children));}
  function simpleBlock(timestamp,payload){var time=timestamp<0?0:Math.min(32767,Math.round(timestamp));return ebml('A3',concat([new Uint8Array([0x81]),be16(time),new Uint8Array([0x80]),payload]));}
  function webm(samples,width,height,fps){var scale=1000000,delta=Math.max(1,Math.round(1000/fps)),header=master('1A45DFA3',[ebml('4286',uintBytes(1)),ebml('42F7',uintBytes(1)),ebml('42F2',uintBytes(4)),ebml('42F3',uintBytes(8)),ebml('4282',ascii('webm')),ebml('4287',uintBytes(2)),ebml('4285',uintBytes(2))]),info=master('1549A966',[ebml('2AD7B1',uintBytes(scale)),ebml('4D80',ascii('AXM Video Codec '+VERSION)),ebml('5741',ascii('AXM Video Codec '+VERSION)),ebml('4489',float64(samples.length*delta))]),video=master('E0',[ebml('B0',uintBytes(width)),ebml('BA',uintBytes(height))]),track=master('AE',[ebml('D7',uintBytes(1)),ebml('73C5',uintBytes(1)),ebml('83',uintBytes(1)),ebml('86',ascii('V_VP8')),ebml('23E383',uintBytes(Math.round(1000000000/fps))),video]),tracks=master('1654AE6B',[track]),cluster=master('1F43B675',[ebml('E7',uintBytes(0))].concat(samples.map(function(sample,index){return simpleBlock(index*delta,sample);}))),segment=master('18538067',[info,tracks,cluster]),bytes=concat([header,segment]),inspection=inspectWebm(bytes);if(!inspection.pass)throw new Error('WebM validation failed: '+inspection.errors.join(', '));return{bytes:bytes,byteLength:bytes.length,dataUrl:dataUrl('video/webm',bytes),inspection:inspection,codec:'V_VP8',frameDeltaMs:delta};}
  function readVint(bytes,offset,forId){if(offset>=bytes.length)return null;var first=bytes[offset],mask=0x80,length=1;while(length<=8&&(first&mask)===0){mask>>=1;length+=1;}if(length>8||offset+length>bytes.length)return null;var value=forId?first:(first&(mask-1));for(var i=1;i<length;i+=1)value=value*256+bytes[offset+i];return{length:length,value:value};}
  function inspectWebm(value){var bytes=asBytes(value),errors=[],elements=[],masters=new Set([0x1a45dfa3,0x18538067,0x1549a966,0x1654ae6b,0xae,0xe0,0x1f43b675]),blocks=[],codec=null,width=null,height=null,timecodeScale=null,duration=null;function parse(start,end,clusterTime){for(var offset=start;offset<end;){var id=readVint(bytes,offset,true);if(!id){errors.push('EBML element id invalid');return;}var size=readVint(bytes,offset+id.length,false);if(!size){errors.push('EBML element size invalid');return;}var payload=offset+id.length+size.length,finish=payload+size.value;if(finish>end){errors.push('EBML element exceeds parent');return;}elements.push({id:id.value,start:offset,payload:payload,end:finish,size:size.value});if(id.value===0xe7){clusterTime=0;for(var i=payload;i<finish;i+=1)clusterTime=clusterTime*256+bytes[i];}else if(id.value===0xa3){var track=readVint(bytes,payload,false);if(!track||payload+track.length+3>finish){errors.push('WebM SimpleBlock header invalid');}else{var at=payload+track.length,rawTime=read16(bytes,at),relative=rawTime&0x8000?rawTime-0x10000:rawTime,flags=bytes[at+2],frame=bytes.subarray(at+3,finish);if(frame.length<10||frame[3]!==0x9d||frame[4]!==0x01||frame[5]!==0x2a)errors.push('WebM VP8 keyframe signature missing');blocks.push({timestamp:(clusterTime||0)+relative,keyframe:(flags&0x80)!==0,bytes:frame.length,payloadStart:at+3,payloadEnd:finish});}}else if(id.value===0x86)codec=text(bytes,payload,size.value);else if(id.value===0xb0){width=0;for(var w=payload;w<finish;w+=1)width=width*256+bytes[w];}else if(id.value===0xba){height=0;for(var h=payload;h<finish;h+=1)height=height*256+bytes[h];}else if(id.value===0x2ad7b1){timecodeScale=0;for(var s=payload;s<finish;s+=1)timecodeScale=timecodeScale*256+bytes[s];}else if(id.value===0x4489&&size.value===8)duration=new DataView(bytes.buffer,bytes.byteOffset+payload,8).getFloat64(0,false);if(masters.has(id.value))parse(payload,finish,clusterTime);offset=finish;}}
    parse(0,bytes.length,0);if(!elements.length||elements[0].id!==0x1a45dfa3)errors.push('WebM EBML header missing');if(!elements.some(function(item){return item.id===0x18538067;}))errors.push('WebM Segment missing');if(codec!=='V_VP8')errors.push('WebM V_VP8 codec declaration missing');if(!width||!height)errors.push('WebM video dimensions missing');if(timecodeScale!==1000000)errors.push('WebM millisecond TimecodeScale missing');if(blocks.length<1)errors.push('WebM contains no SimpleBlock frames');if(blocks.some(function(block){return!block.keyframe;}))errors.push('bounded WebM profile requires keyframe blocks');for(var index=1;index<blocks.length;index+=1)if(blocks[index].timestamp<=blocks[index-1].timestamp)errors.push('WebM frame timestamps are not increasing');var delta=blocks.length>1?blocks[1].timestamp-blocks[0].timestamp:null;return{pass:!errors.length,errors:errors,mime:'video/webm',format:'WebM',codec:codec,profile:'VP8 all-keyframe WebM',bytes:bytes.length,width:width,height:height,frames:blocks.length,timecodeScale:timecodeScale,frameDeltaMs:delta,durationSeconds:duration==null?null:duration/1000,fps:delta?1000/delta:null,blocks:blocks,elements:elements.length};}
  function extractWebpVp8(bytes){bytes=asBytes(bytes);if(text(bytes,0,4)!=='RIFF'||text(bytes,8,4)!=='WEBP')throw new Error('static WebP RIFF signature missing');for(var offset=12;offset+8<=bytes.length;){var type=text(bytes,offset,4),length=bytes[offset+4]|(bytes[offset+5]<<8)|(bytes[offset+6]<<16)|(bytes[offset+7]<<24);if(type==='VP8 ')return bytes.slice(offset+8,offset+8+length);offset+=8+length+(length&1);}throw new Error('static WebP does not contain a VP8 lossy frame');}
  function wrapVp8(payload){var chunk=concat([ascii('VP8 '),new Uint8Array([payload.length&255,(payload.length>>>8)&255,(payload.length>>>16)&255,(payload.length>>>24)&255]),payload,payload.length&1?new Uint8Array([0]):new Uint8Array(0)]),size=4+chunk.length;return concat([ascii('RIFF'),new Uint8Array([size&255,(size>>>8)&255,(size>>>16)&255,(size>>>24)&255]),ascii('WEBP'),chunk]);}
  async function decodeStill(bytes,mime,width,height){var runtime=await Animated.ready(),image=null;try{image=runtime.vips.Image.newFromBuffer(asBytes(bytes),'');var pass=image.width===width&&image.height===height;return{pass:pass,errors:pass?[]:['decoded still-frame dimensions differ'],engine:'libvips',version:runtime.version,width:image.width,height:image.height,bands:image.bands,mime:mime};}catch(error){return{pass:false,errors:['still-frame decode failed: '+String(error.message||error)],engine:'libvips',version:runtime.version,mime:mime};}finally{try{if(image&&image.delete)image.delete();}catch(error){}}}
  async function encode(width,height,frames,options){options=options||{};width=Math.round(Number(width));height=Math.round(Number(height));if(!(width>=16&&height>=16&&width<=640&&height<=360))throw new Error('bounded final-video dimensions must be 16..640 by 16..360');if(!Array.isArray(frames)||frames.length<2||frames.length>120)throw new Error('bounded final-video requires 2..120 RGBA frames');var expected=width*height*4;frames.forEach(function(frame,index){if(asBytes(frame).length!==expected)throw new Error('video frame '+index+' RGBA length mismatch');});var runtime=await Animated.ready(),jpegSamples=[],vp8Samples=[];for(var index=0;index<frames.length;index+=1){var image=null,rgb=null;try{image=runtime.vips.Image.newFromMemory(asBytes(frames[index]),width,height,4,'uchar');rgb=image.flatten({background:[0,0,0]});jpegSamples.push(asBytes(rgb.jpegsaveBuffer({Q:Math.max(50,Math.min(95,Math.round(Number(options.jpegQuality)||85))),optimize_coding:true,keep:'none'})));var webp=asBytes(rgb.webpsaveBuffer({Q:Math.max(50,Math.min(95,Math.round(Number(options.vp8Quality)||82))),lossless:false,smart_subsample:true,effort:4,keep:'none'}));vp8Samples.push(extractWebpVp8(webp));}finally{try{if(rgb&&rgb.delete)rgb.delete();}catch(error){}try{if(image&&image.delete)image.delete();}catch(error){}}}
    var fps=Math.max(1,Math.min(30,Number(options.fps)||24)),formats=Array.isArray(options.formats)?options.formats:['mp4','webm'],result={engine:{name:'libvips JPEG/libwebp + AXM ISO BMFF/WebM muxers',version:runtime.version,wrapperVersion:VERSION},width:width,height:height,frames:frames.length,fps:fps};if(formats.indexOf('mp4')>=0){result.mp4=mp4(jpegSamples,width,height,fps);var mp4First=await decodeStill(jpegSamples[0],'image/jpeg',width,height),mp4Last=await decodeStill(jpegSamples[jpegSamples.length-1],'image/jpeg',width,height);result.mp4.module={pass:mp4First.pass&&mp4Last.pass,first:mp4First,last:mp4Last,errors:(mp4First.errors||[]).concat(mp4Last.errors||[])};}if(formats.indexOf('webm')>=0){result.webm=webm(vp8Samples,width,height,fps);var vp8First=await decodeStill(wrapVp8(vp8Samples[0]),'image/webp',width,height),vp8Last=await decodeStill(wrapVp8(vp8Samples[vp8Samples.length-1]),'image/webp',width,height);result.webm.module={pass:vp8First.pass&&vp8Last.pass,first:vp8First,last:vp8Last,errors:(vp8First.errors||[]).concat(vp8Last.errors||[])};}['mp4','webm'].forEach(function(format){if(result[format]&&(!result[format].inspection.pass||!result[format].module.pass))throw new Error(format+' final validation failed: '+result[format].inspection.errors.concat(result[format].module.errors||[]).join(', '));});return result;}
  return{VERSION:VERSION,encode:encode,mp4:mp4,webm:webm,inspectMp4:inspectMp4,inspectWebm:inspectWebm,extractWebpVp8:extractWebpVp8,wrapVp8:wrapVp8,decodeStill:decodeStill,bytesFromDataUrl:bytesFromDataUrl,dataUrl:dataUrl};
}));
