'use strict';

const zlib = require('zlib');
const U = require('./foundation-utils');

function numericBuffer(value, expected, label) {
  U.ensure(Array.isArray(value) || ArrayBuffer.isView(value), (label || 'numeric buffer') + ' required'); const result = Array.from(value, (item) => U.finite(item, label)); if (expected != null) U.ensure(result.length === expected, (label || 'numeric buffer') + ' length mismatch'); return result;
}

function assessBake(spec) {
  spec = U.clone(spec || {}); const high = U.text(spec.high_mesh_digest, 128, 'high mesh digest'); const low = U.text(spec.low_mesh_digest, 128, 'low mesh digest'); const ray = spec.raycast_receipt; const matrix = spec.render_matrix;
  const maps = U.boundedArray(spec.maps, 3, 20, 'bake maps').map((item) => ({ kind: U.text(item.kind, 30, 'bake map kind'), mime: U.text(item.mime, 80, 'bake map MIME'), pixel_digest: U.text(item.pixel_digest, 128, 'bake map pixel digest'), source_high_digest: U.text(item.source_high_digest, 128, 'bake map high source digest'), target_low_digest: U.text(item.target_low_digest, 128, 'bake map low target digest'), ray_hits: U.finite(item.ray_hits, 'bake ray hits'), miss_ratio: U.finite(item.miss_ratio, 'bake miss ratio') }));
  const required = ['normal', 'ambient-occlusion', 'curvature']; const tangent = spec.tangent_receipt; const checks = [{ name: 'required-maps', pass: required.every((kind) => maps.some((item) => item.kind === kind)) }, { name: 'source-bindings', pass: maps.every((item) => item.source_high_digest === high && item.target_low_digest === low && item.ray_hits > 0) }, { name: 'raycast-not-procedural-flat', pass: ray && ray.status === 'PASS' && ray.high_mesh_digest === high && ray.low_mesh_digest === low }, { name: 'miss-budget', pass: maps.every((item) => item.miss_ratio <= U.finite(spec.max_miss_ratio, 'maximum bake miss ratio')) }, { name: 'tangent-convention', pass: tangent && tangent.status === 'PASS' && tangent.low_mesh_digest === low && tangent.convention === spec.tangent_convention }, { name: 'reference-render', pass: matrix && matrix.status === 'PASS' }];
  const result = { schema: 'axm.high-low-bake-receipt/v1', version: '1.0.0', high_mesh_digest: high, low_mesh_digest: low, tangent_convention: U.text(spec.tangent_convention, 80, 'tangent convention'), maps, raycast_receipt_digest: ray && ray.digest || null, tangent_receipt_digest: tangent && tangent.digest || null, render_matrix_digest: matrix && matrix.digest || null, checks, status: ray && ray.status === 'MISSING_SUBSTRATE' ? 'MISSING_SUBSTRATE' : checks.every((item) => item.pass) ? 'PASS' : 'FAIL' };
  result.digest = U.sha256(result); return result;
}

function normalizeMesh(mesh) {
  const positions = numericBuffer(mesh.positions, null, 'mesh positions'); U.ensure(positions.length % 3 === 0 && positions.length >= 9, 'mesh positions must be XYZ triples'); const vertexCount = positions.length / 3;
  const indices = numericBuffer(mesh.indices, null, 'mesh indices').map(Math.floor); U.ensure(indices.length % 3 === 0 && indices.every((index) => index >= 0 && index < vertexCount), 'mesh triangle indices invalid');
  const uvs = numericBuffer(mesh.uvs, vertexCount * 2, 'mesh UVs');
  return { id: U.text(mesh.id, 100, 'mesh id'), positions, indices, uvs };
}
function topology(mesh) {
  const edgeCounts = new Map(); function edge(a, b) { const key = Math.min(a,b) + ':' + Math.max(a,b); edgeCounts.set(key, (edgeCounts.get(key) || 0) + 1); }
  for (let index = 0; index < mesh.indices.length; index += 3) { const a = mesh.indices[index], b = mesh.indices[index+1], c = mesh.indices[index+2]; edge(a,b); edge(b,c); edge(c,a); }
  return { triangles: mesh.indices.length / 3, vertices: mesh.positions.length / 3, boundary_edges: Array.from(edgeCounts.values()).filter((count) => count === 1).length, nonmanifold_edges: Array.from(edgeCounts.values()).filter((count) => count > 2).length, degenerate_triangles: mesh.indices.filter((_, index) => index % 3 === 0).reduce((count, _, index) => { const offset = index * 3; return count + (new Set(mesh.indices.slice(offset, offset + 3)).size < 3 ? 1 : 0); }, 0) };
}
function silhouetteError(reference, candidate) { reference = numericBuffer(reference, null, 'reference silhouette'); candidate = numericBuffer(candidate, reference.length, 'candidate silhouette'); let union = 0, difference = 0; for (let index = 0; index < reference.length; index += 1) { const a = reference[index] > 0; const b = candidate[index] > 0; if (a || b) union += 1; if (a !== b) difference += 1; } return union ? difference / union : 0; }

function assessLods(spec) {
  spec = U.clone(spec || {}); const lods = U.boundedArray(spec.lods, 2, 12, 'LOD meshes').map((entry) => { const mesh = normalizeMesh(entry.mesh); const json = Buffer.from(JSON.stringify(mesh), 'utf8'); const compressed = zlib.brotliCompressSync(json); const decoded = JSON.parse(zlib.brotliDecompressSync(compressed).toString('utf8')); return { level: Math.floor(U.finite(entry.level, 'LOD level')), mesh, topology: topology(mesh), silhouette_error: silhouetteError(spec.reference_silhouette, entry.silhouette), compressed_base64: compressed.toString('base64'), compressed_digest: U.sha256(compressed), decompressed_digest: U.sha256(decoded), source_digest: U.sha256(mesh) }; });
  lods.sort((a,b) => a.level-b.level); const threshold = U.finite(spec.max_silhouette_error, 'maximum silhouette error'); const checks = [{ name: 'descending-triangles', pass: lods.every((item,index) => index === 0 || item.topology.triangles < lods[index-1].topology.triangles) }, { name: 'manifold', pass: lods.every((item) => item.topology.nonmanifold_edges === 0 && item.topology.degenerate_triangles === 0) }, { name: 'UV-intent', pass: lods.every((item) => item.mesh.uvs.length === item.topology.vertices * 2 && item.mesh.uvs.every((value) => value >= 0 && value <= 1)) }, { name: 'silhouette-budget', pass: lods.every((item) => item.silhouette_error <= threshold) }, { name: 'independent-decompression', pass: lods.every((item) => item.decompressed_digest === item.source_digest) }];
  const result = { schema: 'axm.mesh-lod-compression/v1', version: '1.0.0', source_high_digest: U.text(spec.source_high_digest, 128, 'LOD source digest'), lods, max_silhouette_error: threshold, checks, distance_render_receipt_digest: spec.distance_render_receipt && spec.distance_render_receipt.digest || null, status: checks.every((item) => item.pass) && spec.distance_render_receipt && spec.distance_render_receipt.status === 'PASS' ? 'PASS' : checks.every((item) => item.pass) ? 'TECHNICAL_PASS_LIVE_DISTANCE_RENDER_REQUIRED' : 'FAIL' };
  result.digest = U.sha256(result); return result;
}

function transformPoint(matrix, point) { return [matrix[0]*point[0]+matrix[4]*point[1]+matrix[8]*point[2]+matrix[12], matrix[1]*point[0]+matrix[5]*point[1]+matrix[9]*point[2]+matrix[13], matrix[2]*point[0]+matrix[6]*point[1]+matrix[10]*point[2]+matrix[14]]; }
function deform(spec) {
  spec = U.clone(spec || {}); const positions = numericBuffer(spec.positions, null, 'deform positions'); U.ensure(positions.length % 3 === 0, 'deform positions must be XYZ triples'); const count = positions.length / 3; const joints = U.boundedArray(spec.skin, count, count, 'skin weights'); const matrices = U.boundedArray(spec.joint_matrices, 1, 256, 'joint matrices').map((item) => numericBuffer(item, 16, 'joint matrix')); const shapes = spec.blend_shapes || [];
  const blended = positions.slice(); for (const shape of shapes) { const weight = U.finite(shape.weight, 'blend shape weight'); const deltas = numericBuffer(shape.deltas, positions.length, 'blend shape deltas'); for (let index = 0; index < blended.length; index += 1) blended[index] += deltas[index] * weight; }
  const output = []; const checks = [];
  for (let vertex = 0; vertex < count; vertex += 1) { const influences = U.boundedArray(joints[vertex], 1, 8, 'vertex influences'); const sum = influences.reduce((total,item) => total + U.finite(item.weight, 'skin weight'), 0); checks.push({ vertex, weight_sum: sum, pass: Math.abs(sum-1) <= 1e-5 && influences.every((item) => item.joint >= 0 && item.joint < matrices.length) }); const base = blended.slice(vertex*3,vertex*3+3); const result = [0,0,0]; influences.forEach((item) => { const p = transformPoint(matrices[item.joint], base); result[0] += p[0]*item.weight; result[1] += p[1]*item.weight; result[2] += p[2]*item.weight; }); output.push(...result); }
  return { positions: output, digest: U.sha256(output), checks, pass: checks.every((item) => item.pass) && output.every(Number.isFinite) };
}
function twoBoneIk(spec) { const root = numericBuffer(spec.root,3,'IK root'), target = numericBuffer(spec.target,3,'IK target'); const a=U.finite(spec.upper_length,'upper length'), b=U.finite(spec.lower_length,'lower length'); const distance=Math.hypot(target[0]-root[0],target[1]-root[1],target[2]-root[2]); const clamped=Math.max(Math.abs(a-b)+1e-9,Math.min(a+b-1e-9,distance)); const elbowAngle=Math.acos(Math.max(-1,Math.min(1,(a*a+b*b-clamped*clamped)/(2*a*b)))); const shoulderAngle=Math.acos(Math.max(-1,Math.min(1,(a*a+clamped*clamped-b*b)/(2*a*clamped)))); return { distance, reachable: distance<=a+b && distance>=Math.abs(a-b), shoulder_angle: shoulderAngle, elbow_angle: Math.PI-elbowAngle, digest: U.sha256([root,target,a,b]) }; }
function assessAnimation(spec) {
  spec = U.clone(spec || {}); const frames = U.boundedArray(spec.frames, 2, 10000, 'deformation frames').map((frame) => ({ time_seconds: U.finite(frame.time_seconds,'frame time'), deformation: deform(frame.deformation), root_motion: numericBuffer(frame.root_motion || [0,0,0],3,'root motion'), render_receipt: U.clone(frame.render_receipt) })); const checks=[{name:'timestamps',pass:frames.every((item,index)=>index===0||item.time_seconds>frames[index-1].time_seconds)},{name:'valid-deformation',pass:frames.every((item)=>item.deformation.pass)},{name:'visible-change',pass:new Set(frames.map((item)=>item.deformation.digest)).size>1},{name:'rendered-mesh',pass:frames.every((item)=>item.render_receipt&&item.render_receipt.status==='PASS'&&item.render_receipt.mesh_digest===spec.mesh_digest)},{name:'root-motion-bounded',pass:frames.every((item)=>Math.hypot(...item.root_motion)<=U.finite(spec.max_root_motion_per_frame,'root motion budget'))},{name:'retarget-map',pass:spec.retarget_receipt&&spec.retarget_receipt.status==='PASS'},{name:'IK-FK',pass:spec.ik_receipt&&spec.ik_receipt.status==='PASS'}]; const result={schema:'axm.character-deformation-receipt/v1',version:'1.0.0',mesh_digest:U.text(spec.mesh_digest,128,'character mesh digest'),frames,checks,status:checks.every((item)=>item.pass)?'PASS':'FAIL'}; result.digest=U.sha256(result); return result;
}

function assessAovs(spec) {
  spec = U.clone(spec || {}); const beauty = numericBuffer(spec.beauty, null, 'beauty pixels'); const aovs = U.boundedArray(spec.aovs, 2, 20, 'AOVs').map((item)=>({name:U.text(item.name,40,'AOV name'),pixels:numericBuffer(item.pixels,beauty.length,'AOV pixels'),digest:U.sha256(item.pixels)})); let squared=0,max=0; for(let index=0;index<beauty.length;index+=1){const recomposed=aovs.reduce((sum,item)=>sum+item.pixels[index],0);const error=Math.abs(recomposed-beauty[index]);squared+=error*error;max=Math.max(max,error);} const rmse=Math.sqrt(squared/beauty.length); const renderer=spec.renderer_receipt; const result={schema:'axm.lookdev-aov-receipt/v1',version:'1.0.0',scene_digest:U.text(spec.scene_digest,128,'lookdev scene digest'),camera:U.clone(spec.camera),lights:U.clone(spec.lights),exposure:U.finite(spec.exposure,'lookdev exposure'),beauty_digest:U.sha256(beauty),aovs:aovs.map((item)=>({name:item.name,digest:item.digest})),recomposition:{rmse,max_error:max,threshold:U.finite(spec.max_error,'AOV error threshold')},renderer_receipt_digest:renderer&&renderer.digest||null,status:renderer&&renderer.status==='PASS'&&rmse<=spec.max_error&&max<=spec.max_error?'PASS':renderer&&renderer.status==='MISSING_SUBSTRATE'?'MISSING_SUBSTRATE':'FAIL'}; result.digest=U.sha256(result); return result;
}

function seeded(seed){let state=Number.parseInt(U.sha256(seed).slice(0,8),16)>>>0;return()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};}
function simulate(spec) {
  spec=U.clone(spec||{}); const frames=Math.floor(U.finite(spec.frames,'simulation frames')),dt=U.finite(spec.dt,'simulation timestep'); U.ensure(frames>=2&&frames<=10000&&dt>0&&dt<=0.1,'simulation bounds invalid'); const random=seeded(U.text(spec.seed,100,'simulation seed')); const particles=U.boundedArray(spec.particles,1,100000,'simulation particles').map((item)=>({position:numericBuffer(item.position,3,'particle position'),velocity:numericBuffer(item.velocity,3,'particle velocity'),inverse_mass:U.finite(item.inverse_mass==null?1:item.inverse_mass,'inverse mass')})); particles.forEach((item)=>{item.velocity[0]+=(random()-.5)*(spec.jitter||0);item.velocity[2]+=(random()-.5)*(spec.jitter||0);}); const constraints=U.boundedArray(spec.constraints||[],0,200000,'simulation constraints').map((item)=>({a:Math.floor(item.a),b:Math.floor(item.b),length:U.finite(item.length,'constraint length')})); const cache=[]; for(let frame=0;frame<frames;frame+=1){for(const particle of particles){if(particle.inverse_mass<=0)continue;particle.velocity[1]+=U.finite(spec.gravity==null?-9.81:spec.gravity,'gravity')*dt;for(let axis=0;axis<3;axis+=1)particle.position[axis]+=particle.velocity[axis]*dt;if(particle.position[1]<0){particle.position[1]=0;particle.velocity[1]*=-U.finite(spec.bounce||0,'bounce');}}for(let iteration=0;iteration<2;iteration+=1)for(const constraint of constraints){const a=particles[constraint.a],b=particles[constraint.b];U.ensure(a&&b,'simulation constraint particle missing');const dx=b.position[0]-a.position[0],dy=b.position[1]-a.position[1],dz=b.position[2]-a.position[2],length=Math.hypot(dx,dy,dz)||1,error=(length-constraint.length)/length/2;if(a.inverse_mass>0){a.position[0]+=dx*error;a.position[1]+=dy*error;a.position[2]+=dz*error;}if(b.inverse_mass>0){b.position[0]-=dx*error;b.position[1]-=dy*error;b.position[2]-=dz*error;}}cache.push({frame,time_seconds:frame*dt,positions:particles.flatMap((item)=>item.position),digest:U.sha256(particles.flatMap((item)=>item.position))});} const bytes=Buffer.from(JSON.stringify(cache),'utf8'); const checks=[{name:'visible-change',pass:new Set(cache.map((item)=>item.digest)).size>1},{name:'finite',pass:cache.every((item)=>item.positions.every(Number.isFinite))},{name:'cache-budget',pass:bytes.length<=U.finite(spec.max_cache_bytes,'cache budget')},{name:'particle-budget',pass:particles.length<=U.finite(spec.max_particles,'particle budget')}]; const result={schema:'axm.seeded-simulation-cache/v1',version:'1.0.0',kind:U.text(spec.kind,40,'simulation kind'),seed:spec.seed,settings_digest:U.sha256(spec),frames:cache,cache_bytes:bytes.length,cache_digest:U.sha256(bytes),checks,status:checks.every((item)=>item.pass)?'PASS':'FAIL',native_solver_comparison:spec.native_solver_receipt&&spec.native_solver_receipt.status||'NOT_PROVIDED'}; result.digest=U.sha256(result); return result;
}

function createWorld(spec) {
  spec=U.clone(spec||{}); const width=Math.floor(U.finite(spec.width,'world width')),height=Math.floor(U.finite(spec.height,'world height')),regionSize=Math.floor(U.finite(spec.region_size,'world region size')); U.ensure(width>0&&height>0&&width*height<=16777216&&regionSize>0,'world dimensions invalid'); const seed=U.text(spec.seed,100,'world seed'); const heights=[]; for(let y=0;y<height;y+=1)for(let x=0;x<width;x+=1){const hash=Number.parseInt(U.sha256(seed+'|'+x+'|'+y).slice(0,8),16)/0xffffffff;heights.push(Number((hash*U.finite(spec.max_height,'world max height')).toFixed(6)));} const regions=[];for(let y=0;y<height;y+=regionSize)for(let x=0;x<width;x+=regionSize)regions.push({id:`r-${x}-${y}`,x,y,width:Math.min(regionSize,width-x),height:Math.min(regionSize,height-y),height_digest:U.sha256(Array.from({length:Math.min(regionSize,height-y)},(_,row)=>heights.slice((y+row)*width+x,(y+row)*width+x+Math.min(regionSize,width-x))))}); const prefabs=U.boundedArray(spec.prefabs||[],0,100000,'world prefabs').map((item)=>({id:U.text(item.id,100,'prefab id'),asset_digest:U.text(item.asset_digest,128,'prefab asset digest'),position:numericBuffer(item.position,3,'prefab position'),collision:U.clone(item.collision)})); const spawns=U.boundedArray(spec.spawn_markers,1,10000,'spawn markers').map((item)=>({id:U.text(item.id,100,'spawn id'),position:numericBuffer(item.position,3,'spawn position'),kind:U.text(item.kind,40,'spawn kind')})); const walkable=heights.map((value,index)=>{const x=index%width,y=Math.floor(index/width),right=x+1<width?heights[index+1]:value,down=y+1<height?heights[index+width]:value;return Math.max(Math.abs(right-value),Math.abs(down-value))<=U.finite(spec.max_walk_slope,'walk slope');}); const world={schema:'axm.streamed-world/v1',version:'1.0.0',id:U.text(spec.id,100,'world id'),seed,width,height,region_size:regionSize,heightfield:heights,heightfield_digest:U.sha256(heights),tilemap:U.clone(spec.tilemap),regions,prefabs,spawn_markers:spawns,navigation:{walkable_digest:U.sha256(walkable),walkable_cells:walkable.filter(Boolean).length},budgets:U.clone(spec.budgets),native_runtime_receipt_digest:spec.native_runtime_receipt&&spec.native_runtime_receipt.digest||null,status:spec.native_runtime_receipt&&spec.native_runtime_receipt.status==='PASS'?'PASS':'TECHNICAL_WORLD_PACKAGE_NATIVE_TRAVERSAL_REQUIRED'}; world.digest=U.sha256(world);return world;
}
function streamAt(world,position,radius){U.ensure(world&&world.schema==='axm.streamed-world/v1','streamed world required');position=numericBuffer(position,2,'stream position');radius=U.finite(radius,'stream radius');const loaded=world.regions.filter((region)=>{const cx=region.x+region.width/2,cy=region.y+region.height/2;return Math.hypot(cx-position[0],cy-position[1])<=radius+Math.hypot(region.width,region.height)/2;}).map((item)=>item.id).sort();const bytes=loaded.length*U.finite(world.budgets.bytes_per_region,'bytes per region');return{schema:'axm.world-stream-receipt/v1',world_digest:world.digest,position,radius,loaded_regions:loaded,estimated_bytes:bytes,status:bytes<=world.budgets.max_stream_bytes?'PASS':'BUDGET_EXCEEDED',digest:U.sha256([world.digest,position,radius,loaded])};}

module.exports={assessBake,normalizeMesh,topology,silhouetteError,assessLods,deform,twoBoneIk,assessAnimation,assessAovs,simulate,createWorld,streamAt};
