'use strict';

const U=require('./foundation-utils');
const CreativeHands=require('../creative-hands-service');

const PLAN_SCHEMA='axm.creative-flow-plan/v1';
const RESULT_SCHEMA='axm.creative-flow-result/v1';
const DISCOVERY_SCHEMA='axm.creative-flow-discovery/v1';
const MAX_STEPS=128;
const MAX_INPUT_BYTES=64*1024*1024;

function tokens(value){return Array.from(new Set(String(value||'').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean))).sort();}
function score(query,hand){const q=tokens(query);if(!q.length)return 0;const corpus=tokens([hand.id,hand.title,hand.family,hand.operation,hand.truth].join(' '));const set=new Set(corpus);let matched=0;for(const token of q)if(set.has(token))matched+=1;let result=matched*20;if(String(hand.id).toLowerCase()===String(query).toLowerCase())result+=1000;if(String(hand.operation).toLowerCase()===String(query).toLowerCase())result+=300;if(String(hand.family).toLowerCase()===String(query).toLowerCase())result+=200;return result;}
function catalog(){return CreativeHands.list().map((hand)=>({id:hand.id,title:hand.title,family:hand.family,operation:hand.operation,state:hand.state,deterministic:hand.deterministic===true,outputs:hand.outputs||[],limits:hand.limits||{},digest:hand.digest}));}
function summary(){const audit=CreativeHands.audit(),recipes=CreativeHands.recipeRegistry();const value={schema:'axm.creative-flow-summary/v1',version:'1.0.0',state:'EXECUTABLE',public_hands:audit.total,callable_recipes:recipes.count,hand_audit_digest:audit.digest,recipe_registry_digest:recipes.digest,max_steps:MAX_STEPS,selection_policy:'exact selectors or unique deterministic score; ties HOLD rather than guess',execution_policy:'in-memory candidate state; supplied canonical state is never mutated by the flow runtime'};value.digest=U.sha256(value);return value;}
function discover(spec){spec=U.clone(spec||{});let rows=catalog();if(spec.id)rows=rows.filter((h)=>h.id===String(spec.id));if(spec.family)rows=rows.filter((h)=>h.family===String(spec.family));if(spec.operation)rows=rows.filter((h)=>h.operation===String(spec.operation));const query=String(spec.query||'').trim();rows=rows.map((h)=>Object.assign({},h,{score:query?score(query,h):0}));if(query)rows=rows.filter((h)=>h.score>0);rows.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));const limit=Math.max(1,Math.min(100,Math.floor(Number(spec.limit||20))));const matches=rows.slice(0,limit),top=matches.length?matches[0].score:null,tied_top=top==null?[]:matches.filter((h)=>h.score===top).map((h)=>h.id);let status='MATCHES';if(!matches.length)status='HOLD_NO_MATCH';else if(spec.require_unique===true&&tied_top.length!==1)status='HOLD_AMBIGUOUS';const value={schema:DISCOVERY_SCHEMA,version:'1.0.0',status,query:query||null,filters:{id:spec.id||null,family:spec.family||null,operation:spec.operation||null},matches,tied_top};value.digest=U.sha256(value);return value;}
function collectRefs(value,out){out=out||[];if(Array.isArray(value)){for(const row of value)collectRefs(row,out);return out;}if(!value||typeof value!=='object')return out;if(Object.keys(value).length===1&&typeof value.$ref==='string'){out.push(String(value.$ref));return out;}for(const child of Object.values(value))collectRefs(child,out);return out;}
function collectStateRefs(value,out){out=out||[];if(Array.isArray(value)){for(const row of value)collectStateRefs(row,out);return out;}if(!value||typeof value!=='object')return out;if(Object.keys(value).length===1&&typeof value.$state==='string'){out.push(String(value.$state));return out;}for(const child of Object.values(value))collectStateRefs(child,out);return out;}
function pathGet(root,path,label){let value=root;for(const segment of path){U.ensure(value!=null&&Object.prototype.hasOwnProperty.call(Object(value),segment),(label||'reference')+' missing path segment '+segment);value=value[segment];}return value;}
function resolveValue(value,workspace){if(Array.isArray(value))return value.map((row)=>resolveValue(row,workspace));if(!value||typeof value!=='object')return value;if(Object.keys(value).length===1&&typeof value.$ref==='string'){const parts=value.$ref.split('.').filter(Boolean),step=parts.shift();U.ensure(step&&workspace.steps[step],"unknown step reference: "+value.$ref);return pathGet(workspace.steps[step],parts,'step reference');}if(Object.keys(value).length===1&&typeof value.$state==='string'){const parts=value.$state.split('.').filter(Boolean),name=parts.shift();U.ensure(name&&Object.prototype.hasOwnProperty.call(workspace.state,name),"unknown state reference: "+value.$state);return pathGet(workspace.state[name],parts,'state reference');}if(Object.keys(value).length===1&&Object.prototype.hasOwnProperty.call(value,'$literal'))return value.$literal;const out={};for(const [key,child] of Object.entries(value))out[key]=resolveValue(child,workspace);return out;}
function chooseHand(step,goal){if(step.hand_id){const hand=CreativeHands.get(String(step.hand_id));return hand?{status:'READY',kind:'hand',id:hand.id,hand}: {status:'HOLD_NO_MATCH',reason:'unknown hand_id '+step.hand_id};}if(step.recipe_id){const recipe=CreativeHands.recipeRegistry().tools.find((tool)=>tool.id===String(step.recipe_id));return recipe?{status:'READY',kind:'recipe',id:recipe.id,recipe}: {status:'HOLD_NO_MATCH',reason:'unknown recipe_id '+step.recipe_id};}const selector=Object.assign({},step.selector||{});if(selector.from_goal===true&&!selector.query)selector.query=goal||'';selector.require_unique=true;const found=discover(selector);if(found.status!=='MATCHES'||found.matches.length!==1)return{status:found.status,reason:'selector did not resolve uniquely',discovery:found};return{status:'READY',kind:'hand',id:found.matches[0].id,hand:found.matches[0]};}
function topological(steps){const byId=new Map(steps.map((s)=>[s.id,s])),indegree=new Map(),next=new Map();for(const s of steps){indegree.set(s.id,0);next.set(s.id,[]);}for(const s of steps)for(const dep of s.dependencies){U.ensure(byId.has(dep),'unknown dependency '+dep+' for '+s.id);U.ensure(dep!==s.id,'step cannot depend on itself: '+s.id);indegree.set(s.id,indegree.get(s.id)+1);next.get(dep).push(s.id);}const queue=Array.from(indegree.entries()).filter(([,n])=>n===0).map(([id])=>id).sort(),order=[];while(queue.length){const id=queue.shift();order.push(id);for(const child of next.get(id).slice().sort()){indegree.set(child,indegree.get(child)-1);if(indegree.get(child)===0){queue.push(child);queue.sort();}}}U.ensure(order.length===steps.length,'creative flow contains a dependency cycle');return order;}
function compile(request){request=U.clone(request||{});const rawSteps=U.boundedArray(request.steps||[],1,MAX_STEPS,'creative flow steps'),initialState=request.state&&typeof request.state==='object'&&!Array.isArray(request.state)?request.state:{};U.ensure(U.jsonBytes({state:initialState,steps:rawSteps})<=MAX_INPUT_BYTES,'creative flow input exceeds 64 MiB');const initialNames=new Set(Object.keys(initialState)),ids=new Set(),steps=[],goal=String(request.goal||'').trim();for(let index=0;index<rawSteps.length;index++){const raw=rawSteps[index]||{},id=U.text(raw.id||('step-'+(index+1)),100,'step id');U.ensure(!ids.has(id),'duplicate creative flow step id: '+id);ids.add(id);const operatorCount=(raw.hand_id?1:0)+(raw.recipe_id?1:0)+(raw.selector?1:0);U.ensure(operatorCount===1,'step '+id+' must specify exactly one of hand_id, recipe_id or selector');U.ensure(!raw.args||(!Array.isArray(raw.args)&&typeof raw.args==='object'),'step '+id+' args must be an object');const chosen=chooseHand(raw,goal);if(chosen.status!=='READY')return{schema:PLAN_SCHEMA,version:'1.0.0',status:chosen.status,hold:{step_id:id,reason:chosen.reason,discovery:chosen.discovery||null},goal:goal||null};const refs=collectRefs(raw.args||{}),implicit=refs.map((ref)=>ref.split('.')[0]).filter(Boolean),declared=raw.depends_on==null?[]:U.boundedArray(raw.depends_on,0,MAX_STEPS,'depends_on').map(String),dependencies=Array.from(new Set([...declared,...implicit])).sort();steps.push({id,kind:chosen.kind,operation_id:chosen.id,dependencies,args:raw.args||{},save_as:raw.save_as?U.text(raw.save_as,100,'save_as'):null});}
  const producers=new Map();for(const step of steps)if(step.save_as){U.ensure(!initialNames.has(step.save_as),'save_as cannot overwrite initial state in v1: '+step.save_as);U.ensure(!producers.has(step.save_as),'duplicate save_as state name: '+step.save_as);producers.set(step.save_as,step.id);}for(const step of steps){for(const stateRef of collectStateRefs(step.args)){const name=stateRef.split('.')[0];if(initialNames.has(name))continue;U.ensure(producers.has(name),'state reference '+name+' has no producer');const producer=producers.get(name);U.ensure(producer!==step.id,'step '+step.id+' cannot consume its own save_as state '+name);step.dependencies=Array.from(new Set([...step.dependencies,producer])).sort();}}
  const order=topological(steps),byId=Object.fromEntries(steps.map((s)=>[s.id,s])),available=new Set(initialNames);for(const id of order){const step=byId[id];for(const stateRef of collectStateRefs(step.args)){const name=stateRef.split('.')[0];U.ensure(available.has(name),'state reference '+name+' is unavailable before '+id);}if(step.save_as)available.add(step.save_as);}const audit=CreativeHands.audit(),recipes=CreativeHands.recipeRegistry(),plan={schema:PLAN_SCHEMA,version:'1.0.0',status:'READY',goal:goal||null,initial_state_digest:U.sha256(initialState),hand_audit_digest:audit.digest,recipe_registry_digest:recipes.digest,steps,order,final_state_names:Array.from(available).sort()};plan.digest=U.sha256(plan);return plan;}
function primary(executed){let value=executed;for(let depth=0;depth<4&&value&&typeof value==='object';depth++){if(value.schema==='axm.creative-tool-recipe/v1'&&value.result){value=value.result;continue;}if(value.schema==='axm.creative-executable-hand-result/v1'&&Object.prototype.hasOwnProperty.call(value,'result')){value=value.result;continue;}break;}return value;}
function execute(request){const plan=compile(request);if(plan.status!=='READY')return{schema:RESULT_SCHEMA,version:'1.0.0',status:plan.status,candidate_ready:false,source_state_mutated:false,plan};const workspace={state:U.clone(request.state&&typeof request.state==='object'?request.state:{}),steps:{}},receipts=[];for(const id of plan.order){const step=plan.steps.find((s)=>s.id===id);try{const args=resolveValue(step.args,workspace),input_digest=U.sha256(args),executed=step.kind==='recipe'?CreativeHands.invokeRecipe(step.operation_id,args):CreativeHands.invoke(step.operation_id,args),output=primary(executed),output_digest=output&&typeof output==='object'&&typeof output.digest==='string'?output.digest:U.sha256(output);workspace.steps[id]=executed;if(step.save_as)workspace.state[step.save_as]=output;const receipt={step_id:id,kind:step.kind,operation_id:step.operation_id,dependencies:step.dependencies,input_digest,output_digest,status:'PASS'};receipt.digest=U.sha256(receipt);receipts.push(receipt);}catch(error){const failure={step_id:id,kind:step.kind,operation_id:step.operation_id,message:String(error&&error.message||error)};failure.digest=U.sha256(failure);return{schema:RESULT_SCHEMA,version:'1.0.0',status:'HOLD_EXECUTION_FAILED',candidate_ready:false,source_state_mutated:false,plan_digest:plan.digest,initial_state_digest:plan.initial_state_digest,receipts,failure,partial_candidate_state_digest:U.sha256(workspace.state)};}}const final_state_digest=U.sha256(workspace.state),value={schema:RESULT_SCHEMA,version:'1.0.0',status:'PASS',candidate_ready:true,source_state_mutated:false,plan_digest:plan.digest,initial_state_digest:plan.initial_state_digest,final_state_digest,receipts,final_state:workspace.state};if(request.expose&&typeof request.expose==='object'){value.outputs={};for(const [name,ref] of Object.entries(request.expose))value.outputs[name]=resolveValue(typeof ref==='string'?{$ref:ref}:ref,workspace);}value.digest=U.sha256({plan_digest:value.plan_digest,initial_state_digest:value.initial_state_digest,final_state_digest:value.final_state_digest,receipts:value.receipts,outputs:value.outputs||null});return value;}
function run(request){request=U.clone(request||{});const mode=String(request.mode||((request.steps||[]).length?'execute':'discover'));if(mode==='summary')return summary();if(mode==='discover')return discover(request.discovery||{query:request.goal||'',limit:request.limit||20});if(mode==='plan'){if(!(request.steps||[]).length){const discovery=discover({query:request.goal||'',limit:request.limit||20});return{schema:PLAN_SCHEMA,version:'1.0.0',status:'HOLD_PLAN_REQUIRED',goal:request.goal||null,discovery,truth:'V1 discovers candidate hands but does not invent an execution plan from prose.'};}return compile(request);}if(mode==='execute')return execute(request);throw new Error('unsupported creative flow mode: '+mode);}

module.exports={PLAN_SCHEMA,RESULT_SCHEMA,DISCOVERY_SCHEMA,MAX_STEPS,summary,catalog,discover,compile,execute,run};
