'use strict';

module.exports = Object.freeze({
  qualityGate: require('./quality-gate'),
  familyCoherence: require('./family-coherence'),
  conformance: require('./conformance'),
  editKernel: require('./edit-kernel'),
  runtimeSubstrates: require('./runtime-substrates'),
  negotiationSdk: require('./negotiation-sdk'),
  roundTripLedger: require('./roundtrip-ledger'),
  benchmark: require('./benchmark'),
  fuzzHarness: require('./fuzz-harness'),
  extensionSandbox: require('./extension-sandbox'),
  nativeAdapters: require('./native-adapters'),
  externalValidators: require('./external-validators'),
  rendererMatrix: require('./renderer-matrix'),
  textureMatrix: require('./texture-matrix'),
  dtcgTokens: require('./dtcg-tokens'),
  accessibilityJourney: require('./accessibility-journey'),
  interactivePrototype: require('./interactive-prototype'),
  rasterDocument: require('./raster-document'),
  vectorEngine: require('./vector-engine'),
  typographyStory: require('./typography-story'),
  softgoodsProduction: require('./softgoods-production'),
  manufacturing: require('./manufacturing'),
  advanced3d: require('./advanced-3d'),
  audioProduction: require('./audio-production'),
  videoProduction: require('./video-production'),
});
