'use strict';
const U=require('./foundation-utils');
const Geometry=require('../../../tools/spatial-studio/spatial-geometry');
const SCHEMA='axm.precision-mesh/v1';
const MAX_VERTICES=200000,MAX_TRIANGLES=400000;
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function finite(v,l){return U.finite(v,l);}function arr(v,l){U.ensure(Array.isArray(v)||ArrayBuffer.isView(v),(l||'array')+' required');return Array.from(v,(x)=>finite(x,l));}
function vec3(v,l){const a=arr(v,l);U.ensure(a.length===3,(l||'vec3')+' must have three values');return a;}function digestMesh(m){return U.sha256({positions:m.positions,normals:m.normals,uvs:m.uvs,indices:m.indices});}
function create(spec){spec=U.clone(spec||{});const positions=arr(spec.positions,'mesh positions'),indices=arr(spec.indices,'mesh indices').map(Math.floor);U.ensure(positions.length>=9&&positions.length%3===0,'mesh positions must be XYZ triples');const vertices=positions.length/3;U.ensure(vertices<=MAX_VERTICES,'mesh vertex budget exceeded');U.ensure(indices.length>=3&&indices.length%3===0&&indices.length/3<=MAX_TRIANGLES,'mesh triangle budget exceeded');U.ensure(indices.every((i)=>i>=0&&i<vertices),'mesh index out of range');let normals=spec.normals==null?null:arr(spec.normals,'mesh normals'),uvs=spec.uvs==null?new Array(vertices*2).fill(0):arr(spec.uvs,'mesh uvs');if(normals)U.ensure(normals.length===positions.length,'mesh normals length mismatch');U.ensure(uvs.length===vertices*2,'mesh uvs length mismatch');let value={schema:SCHEMA,version:'1.0.0',id:String(spec.id||'mesh'),positions,indices,uvs,normals:normals||new Array(positions.length).fill(0),metadata:U.clone(spec.metadata||{})};if(!normals)value=recalcNormals(value);value.digest=digestMesh(value);return value;}
function primitive(type,spec){spec=U.clone(spec||{});type=U.text(type,30,'mesh primitive');U.ensure(['cube','sphere','cylinder','cone','plane','torus'].includes(type),'unsupported mesh primitive');const detail=Math.floor(finite(spec.detail==null?24:spec.detail,'mesh detail'));U.ensure(detail>=3&&detail<=64,'mesh detail outside 3..64');const built=Geometry.build(type,detail,{inflate:finite(spec.inflate==null?0:spec.inflate,'primitive inflate'),twist:finite(spec.twist==null?0:spec.twist,'primitive twist')});let mesh=create({id:spec.id||type,positions:Array.from(built.positions),normals:Array.from(built.normals),indices:Array.from(built.indices),metadata:{primitive:type,detail}});mesh=planarUv(mesh,'y');return mesh;}
function mapPositions(mesh,fn,label){U.ensure(mesh&&mesh.schema===SCHEMA,'precision mesh required');const positions=mesh.positions.slice();for(let i=0;i<positions.length;i+=3){const p=fn([positions[i],positions[i+1],positions[i+2]],i/3);U.ensure(Array.isArray(p)&&p.length===3&&p.every(Number.isFinite),(label||'mesh transform')+' returned invalid point');positions[i]=p[0];positions[i+1]=p[1];positions[i+2]=p[2];}return recalcNormals(create({id:mesh.id,positions,indices:mesh.indices,uvs:mesh.uvs,metadata:Object.assign({},mesh.metadata,{last_operation:label})}));}
function translate(mesh,v){v=vec3(v,'translation');return mapPositions(mesh,(p)=>[p[0]+v[0],p[1]+v[1],p[2]+v[2]],'translate');}
function scale(mesh,v){v=typeof v==='number'?[v,v,v]:vec3(v,'scale');U.ensure(v.every((x)=>Number.isFinite(x)&&Math.abs(x)>1e-12),'scale components cannot be zero');return mapPositions(mesh,(p)=>[p[0]*v[0],p[1]*v[1],p[2]*v[2]],'scale');}
function rotate(mesh,axis,degrees){axis=String(axis);U.ensure(['x','y','z'].includes(axis),'rotation axis invalid');const a=finite(degrees,'rotation degrees')*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return mapPositions(mesh,(p)=>axis==='x'?[p[0],p[1]*c-p[2]*s,p[1]*s+p[2]*c]:axis==='y'?[p[0]*c+p[2]*s,p[1],-p[0]*s+p[2]*c]:[p[0]*c-p[1]*s,p[0]*s+p[1]*c,p[2]],'rotate-'+axis);}
function mirror(mesh,axis){axis=String(axis);U.ensure(['x','y','z'].includes(axis),'mirror axis invalid');const out=mapPositions(mesh,(p)=>p.map((v,i)=>i==='xyz'.indexOf(axis)?-v:v),'mirror-'+axis);return flipWinding(out);}
function recalcNormals(mesh){U.ensure(mesh&&mesh.schema===SCHEMA,'precision mesh required');const n=new Array(mesh.positions.length).fill(0),p=mesh.positions;for(let i=0;i<mesh.indices.length;i+=3){const ia=mesh.indices[i]*3,ib=mesh.indices[i+1]*3,ic=mesh.indices[i+2]*3,ax=p[ia],ay=p[ia+1],az=p[ia+2],ux=p[ib]-ax,uy=p[ib+1]-ay,uz=p[ib+2]-az,vx=p[ic]-ax,vy=p[ic+1]-ay,vz=p[ic+2]-az,nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx;for(const j of [ia,ib,ic]){n[j]+=nx;n[j+1]+=ny;n[j+2]+=nz;}}for(let i=0;i<n.length;i+=3){const l=Math.hypot(n[i],n[i+1],n[i+2])||1;n[i]/=l;n[i+1]/=l;n[i+2]/=l;}const out=Object.assign({},mesh,{normals:n});out.digest=digestMesh(out);return out;}
function flipWinding(mesh){const idx=mesh.indices.slice();for(let i=0;i<idx.length;i+=3)[idx[i+1],idx[i+2]]=[idx[i+2],idx[i+1]];return recalcNormals(create({id:mesh.id,positions:mesh.positions,indices:idx,uvs:mesh.uvs,metadata:Object.assign({},mesh.metadata,{last_operation:'flip-winding'})}));}
function bounds(mesh){U.ensure(mesh&&mesh.schema===SCHEMA,'precision mesh required');const p=mesh.positions,min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<p.length;i+=3)for(let a=0;a<3;a++){min[a]=Math.min(min[a],p[i+a]);max[a]=Math.max(max[a],p[i+a]);}const size=max.map((v,i)=>v-min[i]),center=max.map((v,i)=>(v+min[i])/2);const result={schema:'axm.precision-mesh-bounds/v1',mesh_digest:mesh.digest,min,max,size,center};result.digest=U.sha256(result);return result;}
function centerOrigin(mesh){const b=bounds(mesh);return translate(mesh,b.center.map((x)=>-x));}
function normalizeScale(mesh,target){target=finite(target==null?2:target,'normalize target');U.ensure(target>0&&target<=1e6,'normalize target invalid');const b=bounds(mesh),largest=Math.max(...b.size);U.ensure(largest>1e-12,'cannot normalize zero-size mesh');return scale(mesh,target/largest);}
function inflate(mesh,amount){amount=finite(amount,'inflate amount');return mapPositions(mesh,(p,i)=>[p[0]+mesh.normals[i*3]*amount,p[1]+mesh.normals[i*3+1]*amount,p[2]+mesh.normals[i*3+2]*amount],'inflate');}
function twist(mesh,degrees){const b=bounds(mesh),height=Math.max(1e-12,b.size[1]),radians=finite(degrees,'twist degrees')*Math.PI/180;return mapPositions(mesh,(p)=>{const t=(p[1]-b.min[1])/height-.5,a=t*radians,c=Math.cos(a),s=Math.sin(a);return[p[0]*c-p[2]*s,p[1],p[0]*s+p[2]*c];},'twist');}
function taper(mesh,factor){factor=finite(factor,'taper factor');U.ensure(Math.abs(factor)<=10,'taper factor invalid');const b=bounds(mesh),h=Math.max(1e-12,b.size[1]);return mapPositions(mesh,(p)=>{const t=(p[1]-b.min[1])/h-.5,s=Math.max(.001,1+t*factor);return[p[0]*s,p[1],p[2]*s];},'taper');}
function bend(mesh,degrees){const b=bounds(mesh),h=Math.max(1e-12,b.size[1]),angle=finite(degrees,'bend degrees')*Math.PI/180;U.ensure(Math.abs(angle)<=Math.PI*4,'bend outside +/-720 degrees');if(Math.abs(angle)<1e-9)return create(mesh);const radius=h/angle;return mapPositions(mesh,(p)=>{const t=(p[1]-b.center[1])/h,a=t*angle;return[p[0],b.center[1]+Math.sin(a)*radius,p[2]+(1-Math.cos(a))*radius];},'bend');}
function flatten(mesh,axis,value){axis=String(axis);U.ensure(['x','y','z'].includes(axis),'flatten axis invalid');value=finite(value==null?0:value,'flatten value');const ai='xyz'.indexOf(axis);return mapPositions(mesh,(p)=>{p[ai]=value;return p;},'flatten-'+axis);}
function seeded(seed){let s=Number.parseInt(U.sha256(String(seed||'mesh-noise')).slice(0,8),16)>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
function noiseDisplace(mesh,spec){spec=U.clone(spec||{});const amount=finite(spec.amount==null?.05:spec.amount,'noise displacement'),rng=seeded(spec.seed);U.ensure(Math.abs(amount)<=100,'noise displacement invalid');return mapPositions(mesh,(p,i)=>{const a=(rng()*2-1)*amount;return[p[0]+mesh.normals[i*3]*a,p[1]+mesh.normals[i*3+1]*a,p[2]+mesh.normals[i*3+2]*a];},'noise-displace');}
function removeDegenerate(mesh,epsilon){epsilon=finite(epsilon==null?1e-10:epsilon,'degenerate epsilon');U.ensure(epsilon>=0,'degenerate epsilon invalid');const p=mesh.positions,idx=[];for(let i=0;i<mesh.indices.length;i+=3){const a=mesh.indices[i],b=mesh.indices[i+1],c=mesh.indices[i+2];if(a===b||b===c||a===c)continue;const ia=a*3,ib=b*3,ic=c*3,ux=p[ib]-p[ia],uy=p[ib+1]-p[ia+1],uz=p[ib+2]-p[ia+2],vx=p[ic]-p[ia],vy=p[ic+1]-p[ia+1],vz=p[ic+2]-p[ia+2],area2=Math.hypot(uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx);if(area2>epsilon)idx.push(a,b,c);}U.ensure(idx.length>=3,'all triangles are degenerate');return recalcNormals(create({id:mesh.id,positions:mesh.positions,indices:idx,uvs:mesh.uvs,metadata:Object.assign({},mesh.metadata,{last_operation:'remove-degenerate'})}));}
function compact(mesh){const used=new Set(mesh.indices),map=new Map(),positions=[],uvs=[];Array.from(used).sort((a,b)=>a-b).forEach((old)=>{map.set(old,positions.length/3);positions.push(...mesh.positions.slice(old*3,old*3+3));uvs.push(...mesh.uvs.slice(old*2,old*2+2));});const indices=mesh.indices.map((i)=>map.get(i));return recalcNormals(create({id:mesh.id,positions,indices,uvs,metadata:Object.assign({},mesh.metadata,{last_operation:'compact'})}));}
function weld(mesh,epsilon){epsilon=finite(epsilon==null?1e-6:epsilon,'weld epsilon');U.ensure(epsilon>0&&epsilon<=1,'weld epsilon invalid');const map=new Map(),remap=[],positions=[],uvs=[];for(let i=0;i<mesh.positions.length;i+=3){const p=mesh.positions.slice(i,i+3),key=p.map((v)=>Math.round(v/epsilon)).join(':');let ni=map.get(key);if(ni==null){ni=positions.length/3;map.set(key,ni);positions.push(...p);uvs.push(...mesh.uvs.slice((i/3)*2,(i/3)*2+2));}remap.push(ni);}const indices=mesh.indices.map((i)=>remap[i]);return removeDegenerate(recalcNormals(create({id:mesh.id,positions,indices,uvs,metadata:Object.assign({},mesh.metadata,{last_operation:'weld',epsilon})})),0);}
function merge(meshes,id){meshes=U.boundedArray(meshes,1,64,'meshes');let positions=[],uvs=[],indices=[],offset=0;for(const m of meshes){U.ensure(m.schema===SCHEMA,'precision mesh required');positions.push(...m.positions);uvs.push(...m.uvs);indices.push(...m.indices.map((i)=>i+offset));offset+=m.positions.length/3;}return recalcNormals(create({id:id||'merged',positions,indices,uvs,metadata:{merged_from:meshes.map((m)=>m.digest)}}));}
function subdivide(mesh){U.ensure(mesh.indices.length/3*4<=MAX_TRIANGLES,'subdivide triangle budget exceeded');let positions=mesh.positions.slice(),uvs=mesh.uvs.slice(),indices=[],cache=new Map();function midpoint(a,b){const key=a<b?a+':'+b:b+':'+a;if(cache.has(key))return cache.get(key);const ai=a*3,bi=b*3,aui=a*2,bui=b*2,n=positions.length/3;positions.push((positions[ai]+positions[bi])/2,(positions[ai+1]+positions[bi+1])/2,(positions[ai+2]+positions[bi+2])/2);uvs.push((uvs[aui]+uvs[bui])/2,(uvs[aui+1]+uvs[bui+1])/2);cache.set(key,n);return n;}for(let i=0;i<mesh.indices.length;i+=3){const a=mesh.indices[i],b=mesh.indices[i+1],c=mesh.indices[i+2],ab=midpoint(a,b),bc=midpoint(b,c),ca=midpoint(c,a);indices.push(a,ab,ca,ab,b,bc,ca,bc,c,ab,bc,ca);}return recalcNormals(create({id:mesh.id,positions,indices,uvs,metadata:Object.assign({},mesh.metadata,{last_operation:'subdivide'})}));}
function planarUv(mesh,axis){axis=String(axis);U.ensure(['x','y','z'].includes(axis),'UV projection axis invalid');const b=bounds(mesh),pairs=axis==='x'?[1,2]:axis==='y'?[0,2]:[0,1],uv=[];for(let i=0;i<mesh.positions.length;i+=3){for(const a of pairs){const span=Math.max(1e-12,b.size[a]);uv.push(clamp((mesh.positions[i+a]-b.min[a])/span,0,1));}}return create({id:mesh.id,positions:mesh.positions,normals:mesh.normals,indices:mesh.indices,uvs:uv,metadata:Object.assign({},mesh.metadata,{uv_projection:'planar-'+axis})});}
function sphericalUv(mesh){const uv=[];for(let i=0;i<mesh.positions.length;i+=3){const x=mesh.positions[i],y=mesh.positions[i+1],z=mesh.positions[i+2],r=Math.hypot(x,y,z)||1;uv.push((Math.atan2(z,x)/(2*Math.PI)+1)%1,Math.acos(clamp(y/r,-1,1))/Math.PI);}return create({id:mesh.id,positions:mesh.positions,normals:mesh.normals,indices:mesh.indices,uvs:uv,metadata:Object.assign({},mesh.metadata,{uv_projection:'spherical'})});}
function cylindricalUv(mesh){const b=bounds(mesh),uv=[];for(let i=0;i<mesh.positions.length;i+=3){const x=mesh.positions[i],y=mesh.positions[i+1],z=mesh.positions[i+2];uv.push((Math.atan2(z,x)/(2*Math.PI)+1)%1,clamp((y-b.min[1])/Math.max(1e-12,b.size[1]),0,1));}return create({id:mesh.id,positions:mesh.positions,normals:mesh.normals,indices:mesh.indices,uvs:uv,metadata:Object.assign({},mesh.metadata,{uv_projection:'cylindrical-y'})});}
function normalizeUv(mesh){let minU=Infinity,minV=Infinity,maxU=-Infinity,maxV=-Infinity;for(let i=0;i<mesh.uvs.length;i+=2){minU=Math.min(minU,mesh.uvs[i]);maxU=Math.max(maxU,mesh.uvs[i]);minV=Math.min(minV,mesh.uvs[i+1]);maxV=Math.max(maxV,mesh.uvs[i+1]);}const su=Math.max(1e-12,maxU-minU),sv=Math.max(1e-12,maxV-minV),uv=mesh.uvs.map((v,i)=>(v-(i%2?minV:minU))/(i%2?sv:su));return create({id:mesh.id,positions:mesh.positions,normals:mesh.normals,indices:mesh.indices,uvs:uv,metadata:Object.assign({},mesh.metadata,{uv_normalized:true})});}
function surfaceArea(mesh){let area=0,p=mesh.positions;for(let i=0;i<mesh.indices.length;i+=3){const a=mesh.indices[i]*3,b=mesh.indices[i+1]*3,c=mesh.indices[i+2]*3,ux=p[b]-p[a],uy=p[b+1]-p[a+1],uz=p[b+2]-p[a+2],vx=p[c]-p[a],vy=p[c+1]-p[a+1],vz=p[c+2]-p[a+2];area+=Math.hypot(uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx)/2;}return{mesh_digest:mesh.digest,surface_area:area,digest:U.sha256({mesh:mesh.digest,area})};}
function signedVolume(mesh){let volume=0,p=mesh.positions;for(let i=0;i<mesh.indices.length;i+=3){const a=mesh.indices[i]*3,b=mesh.indices[i+1]*3,c=mesh.indices[i+2]*3;volume+=(p[a]*(p[b+1]*p[c+2]-p[b+2]*p[c+1])-p[a+1]*(p[b]*p[c+2]-p[b+2]*p[c])+p[a+2]*(p[b]*p[c+1]-p[b+1]*p[c]))/6;}return{mesh_digest:mesh.digest,signed_volume:volume,absolute_volume:Math.abs(volume),digest:U.sha256({mesh:mesh.digest,volume})};}
function centroid(mesh){const p=mesh.positions,c=[0,0,0],n=p.length/3;for(let i=0;i<p.length;i+=3){c[0]+=p[i]/n;c[1]+=p[i+1]/n;c[2]+=p[i+2]/n;}return{mesh_digest:mesh.digest,centroid:c,digest:U.sha256({mesh:mesh.digest,c})};}
function topology(mesh){const edges=new Map();for(let i=0;i<mesh.indices.length;i+=3)for(const [a,b] of [[mesh.indices[i],mesh.indices[i+1]],[mesh.indices[i+1],mesh.indices[i+2]],[mesh.indices[i+2],mesh.indices[i]]]){const k=Math.min(a,b)+':'+Math.max(a,b);edges.set(k,(edges.get(k)||0)+1);}const counts=Array.from(edges.values()),result={mesh_digest:mesh.digest,vertices:mesh.positions.length/3,triangles:mesh.indices.length/3,edges:edges.size,boundary_edges:counts.filter((n)=>n===1).length,nonmanifold_edges:counts.filter((n)=>n>2).length};result.digest=U.sha256(result);return result;}
module.exports={SCHEMA,create,primitive,translate,scale,rotate,mirror,recalcNormals,flipWinding,bounds,centerOrigin,normalizeScale,inflate,twist,taper,bend,flatten,noiseDisplace,removeDegenerate,compact,weld,merge,subdivide,planarUv,sphericalUv,cylindricalUv,normalizeUv,surfaceArea,signedVolume,centroid,topology};