'use strict';

const U = require('./foundation-utils');
const Precision = require('./creative-precision');

const IMAGE_SCHEMA = 'axm.precision-raster/v1';
const MAX_PIXELS = 16777216;
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function int(value,min,max,label){const n=Math.floor(U.finite(value,label));U.ensure(n>=min&&n<=max,(label||'integer')+' outside '+min+'..'+max);return n;}
function bytes(value,expected,label){const out=Buffer.isBuffer(value)?Buffer.from(value):typeof value==='string'?Buffer.from(value,'base64'):Buffer.from(value||[]);U.ensure(out.length===expected,(label||'buffer')+' length mismatch');return out;}
function image(spec){spec=U.clone(spec||{});const width=int(spec.width,1,16384,'image width'),height=int(spec.height,1,16384,'image height');U.ensure(width*height<=MAX_PIXELS,'image pixel budget exceeded');const rgba=bytes(spec.rgba!=null?spec.rgba:spec.rgba8_base64,width*height*4,'image rgba');const result={schema:IMAGE_SCHEMA,version:'1.0.0',width,height,rgba8_base64:rgba.toString('base64'),colour_space:U.text(spec.colour_space||'srgb',80,'colour space'),source_digest:U.text(spec.source_digest||U.sha256(rgba),128,'source digest')};result.digest=U.sha256(result);return result;}
function decode(value){U.ensure(value&&value.schema===IMAGE_SCHEMA,'precision raster required');return{width:value.width,height:value.height,rgba:bytes(value.rgba8_base64,value.width*value.height*4,'image rgba')};}
function luma(r,g,b){return 0.2126*r+0.7152*g+0.0722*b;}
function channelMask(value,channel){const d=decode(value);channel=U.text(channel,20,'channel').toLowerCase();U.ensure(['red','green','blue','alpha','luminance'].includes(channel),'unsupported channel');const out=Buffer.alloc(d.width*d.height);const offset={red:0,green:1,blue:2,alpha:3}[channel];for(let p=0,i=0;p<out.length;p+=1,i+=4)out[p]=channel==='luminance'?Math.round(luma(d.rgba[i],d.rgba[i+1],d.rgba[i+2])):d.rgba[i+offset];return Precision.mask(d.width,d.height,out,{source:'channel',channel,image_digest:value.digest});}
function luminanceRangeMask(value,spec){const d=decode(value);spec=U.clone(spec||{});const low=clamp(U.finite(spec.low==null?0:spec.low,'luminance low'),0,1)*255,high=clamp(U.finite(spec.high==null?1:spec.high,'luminance high'),0,1)*255,soft=Math.max(0,U.finite(spec.softness==null?0:spec.softness,'luminance softness'))*255;U.ensure(high>=low,'luminance high below low');const out=Buffer.alloc(d.width*d.height);for(let p=0,i=0;p<out.length;p+=1,i+=4){const y=luma(d.rgba[i],d.rgba[i+1],d.rgba[i+2]);let a=y>=low&&y<=high?255:0;if(!a&&soft>0){const distance=y<low?low-y:y-high;a=Math.round(255*clamp(1-distance/soft,0,1));}out[p]=a;}return Precision.mask(d.width,d.height,out,{source:'luminance-range',low:low/255,high:high/255,softness:soft/255,image_digest:value.digest});}
function colourDistance(r,g,b,target){return Math.hypot(r-target[0],g-target[1],b-target[2]);}
function colourRangeMask(value,spec){const d=decode(value);spec=U.clone(spec||{});const target=U.boundedArray(spec.target_rgb,3,3,'target rgb').map((v)=>clamp(Math.round(U.finite(v,'target channel')),0,255));const tolerance=clamp(U.finite(spec.tolerance,'colour tolerance'),0,441.67295593),softness=clamp(U.finite(spec.softness==null?0:spec.softness,'colour softness'),0,441.67295593);const out=Buffer.alloc(d.width*d.height);for(let p=0,i=0;p<out.length;p+=1,i+=4){const distance=colourDistance(d.rgba[i],d.rgba[i+1],d.rgba[i+2],target);out[p]=distance<=tolerance?255:softness>0?Math.round(255*clamp(1-(distance-tolerance)/softness,0,1)):0;}return Precision.mask(d.width,d.height,out,{source:'colour-range',target_rgb:target,tolerance,softness,image_digest:value.digest});}
function contiguousColourMask(value,spec){const d=decode(value);spec=U.clone(spec||{});const sx=int(spec.x,0,d.width-1,'seed x'),sy=int(spec.y,0,d.height-1,'seed y');const tolerance=clamp(U.finite(spec.tolerance,'contiguous tolerance'),0,441.67295593),connectivity=int(spec.connectivity==null?4:spec.connectivity,4,8,'connectivity');U.ensure(connectivity===4||connectivity===8,'connectivity must be 4 or 8');const start=(sy*d.width+sx)*4,target=[d.rgba[start],d.rgba[start+1],d.rgba[start+2]];const out=Buffer.alloc(d.width*d.height),seen=Buffer.alloc(d.width*d.height),queue=[[sx,sy]];seen[sy*d.width+sx]=1;const offsets=connectivity===8?[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]:[[1,0],[-1,0],[0,1],[0,-1]];for(let q=0;q<queue.length;q+=1){const [x,y]=queue[q],p=y*d.width+x,i=p*4;if(colourDistance(d.rgba[i],d.rgba[i+1],d.rgba[i+2],target)>tolerance)continue;out[p]=255;for(const [ox,oy] of offsets){const nx=x+ox,ny=y+oy;if(nx<0||ny<0||nx>=d.width||ny>=d.height)continue;const np=ny*d.width+nx;if(!seen[np]){seen[np]=1;queue.push([nx,ny]);}}}return Precision.mask(d.width,d.height,out,{source:'contiguous-colour',seed:{x:sx,y:sy},target_rgb:target,tolerance,connectivity,image_digest:value.digest});}
function edgeMask(value,spec){const d=decode(value);spec=U.clone(spec||{});const threshold=clamp(U.finite(spec.threshold==null?0:spec.threshold,'edge threshold'),0,1)*1020,softness=Math.max(1,U.finite(spec.softness==null?.15:spec.softness,'edge softness')*1020);const lum=new Float64Array(d.width*d.height);for(let p=0,i=0;p<lum.length;p+=1,i+=4)lum[p]=luma(d.rgba[i],d.rgba[i+1],d.rgba[i+2]);const out=Buffer.alloc(lum.length),sample=(x,y)=>lum[clamp(y,0,d.height-1)*d.width+clamp(x,0,d.width-1)];for(let y=0;y<d.height;y+=1)for(let x=0;x<d.width;x+=1){const gx=-sample(x-1,y-1)+sample(x+1,y-1)-2*sample(x-1,y)+2*sample(x+1,y)-sample(x-1,y+1)+sample(x+1,y+1);const gy=-sample(x-1,y-1)-2*sample(x,y-1)-sample(x+1,y-1)+sample(x-1,y+1)+2*sample(x,y+1)+sample(x+1,y+1);const magnitude=Math.hypot(gx,gy);out[y*d.width+x]=Math.round(255*clamp((magnitude-threshold)/softness,0,1));}return Precision.mask(d.width,d.height,out,{source:'sobel-edge',threshold:threshold/1020,softness:softness/1020,image_digest:value.digest});}
module.exports={IMAGE_SCHEMA,image,decode,channelMask,luminanceRangeMask,colourRangeMask,contiguousColourMask,edgeMask};
