"""Build and independently inspect one four-pose expressive character proof.

The original character and all expression/stance geometry are generated by UC.
Each final GLB combines the checked static pose with the portable painted style.
This proves bounded geometry and import behavior, not skeletal animation.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from axm_uc.game_character_expression import apply_character_expression
from axm_uc.game_render_styles import apply_game_render_style
from axm_uc.procedural_3d import build_glb, verify_glb
from axm_uc.rts_mesh import SalvageMesh


VARIANTS = (
    ("neutral", "neutral"),
    ("curious", "mechanic-ready"),
    ("mischief", "comic-sneak"),
    ("alarmed", "victory"),
)
OFFSETS = {"neutral": -5.1, "curious": -1.7, "mischief": 1.7, "alarmed": 5.1}


def character_mesh():
    mesh = SalvageMesh()
    with mesh.part("body", (0, 0, 0)):
        mesh.roundbox("boiler-body", (0, 1.14, 0), (1.45, 1.45, .78), "paint", .16)
        mesh.roundbox("belly-door", (0, 1.04, .45), (.92, .72, .12), "iron", .08)
        mesh.smile((0, 1.04, .53), .22)
        for x in (-.52, .52):
            mesh.ellipsoid("body-rivet", (x, 1.62, .44), (.10, .10, .06), "tin", 7, 4)
    with mesh.part("head", (0, 1.78, 0)):
        mesh.ellipsoid("face-shell", (0, 2.02, .04), (1.42, 1.02, .88), "ivory", 16, 9)
        mesh.roundbox("jaw-guard", (0, 1.72, .30), (.88, .28, .20), "paint", .06)
    with mesh.part("identity_ring", (-.31, 2.10, .49)):
        mesh.ring("signature-monocle", (-.31, 2.10, .49), .31, .055, "signal", axis="z", ratio=.92)
        mesh.pipe("monocle-cable", [(-.54, 1.88, .47), (-.65, 1.64, .35)], .025, "rubber", 7)
    with mesh.part("nose", (0, 1.91, .58)):
        mesh.ellipsoid("duck-beak", (0, 1.91, .58), (.26, .14, .22), "signal", 9, 5)
    with mesh.part("eye_left", (-.31, 2.10, .55)):
        mesh.ellipsoid("big-optic", (-.31, 2.10, .55), (.42, .38, .12), "cyan", 11, 6)
        mesh.ellipsoid("optic-pupil", (-.31, 2.10, .625), (.15, .15, .045), "rubber", 8, 5)
    with mesh.part("eye_right", (.29, 2.10, .52)):
        mesh.ellipsoid("small-optic", (.29, 2.10, .52), (.29, .26, .10), "cyan", 10, 6)
        mesh.ellipsoid("optic-pupil", (.29, 2.10, .585), (.10, .10, .04), "rubber", 7, 4)
    for side, x in (("left", -.31), ("right", .29)):
        with mesh.part(f"brow_{side}", (x, 2.34, .59)):
            mesh.beam("expressive-brow", (x-.17, 2.34, .59), (x+.17, 2.34, .59), .055, .055, "rubber")
    with mesh.part("mouth", (0, 1.70, .57)):
        mesh.pipe("grin", [(-.31, 1.75, .57), (-.17, 1.66, .61), (0, 1.62, .63),
                            (.17, 1.66, .61), (.31, 1.75, .57)], .045, "red", 7)
        for x in (-.17, 0, .17):
            mesh.box("grin-tooth", (x, 1.70, .635), (.10, .12, .035), "ivory")
    with mesh.part("arm_left", (-.82, 1.52, 0)):
        mesh.beam("upper-arm", (-.82, 1.52, 0), (-1.02, .92, .06), .20, .20, "iron")
        mesh.ellipsoid("elbow", (-1.02, .92, .06), (.28, .28, .28), "signal", 9, 5)
        mesh.beam("forearm", (-1.02, .92, .06), (-.99, .45, .16), .18, .18, "tin")
    with mesh.part("arm_right", (.82, 1.52, 0)):
        mesh.beam("upper-arm", (.82, 1.52, 0), (1.02, .92, .06), .20, .20, "iron")
        mesh.ellipsoid("elbow", (1.02, .92, .06), (.28, .28, .28), "red", 9, 5)
        mesh.beam("forearm", (1.02, .92, .06), (.99, .45, .16), .18, .18, "tin")
    with mesh.part("leg_left", (-.42, .48, 0)):
        mesh.beam("spring-leg", (-.42, .48, 0), (-.48, -.06, .02), .24, .24, "signal")
        mesh.roundbox("boot", (-.48, -.15, .14), (.52, .28, .72), "rubber", .09)
    with mesh.part("leg_right", (.42, .48, 0)):
        mesh.beam("spring-leg", (.42, .48, 0), (.48, -.06, .02), .24, .24, "signal")
        mesh.roundbox("boot", (.48, -.15, .14), (.52, .28, .72), "rubber", .09)
    with mesh.part("prop", (-.99, .45, .16)):
        mesh.beam("wrench-handle", (-.99, .45, .16), (-1.08, -.18, .18), .12, .09, "signal")
        mesh.ring("wrench-jaw", (-1.08, -.30, .18), .22, .065, "signal", axis="z", ratio=.70)
    with mesh.part("backpack", (0, 1.25, -.45)):
        mesh.roundbox("scrap-pack", (0, 1.28, -.49), (1.05, .92, .30), "red", .11)
        mesh.pipe("exhaust", [(.36, 1.44, -.55), (.49, 2.01, -.51)], .08, "iron", 9)
    with mesh.part("antenna", (.42, 2.42, .02)):
        mesh.pipe("antenna", [(.42, 2.42, .02), (.55, 2.91, .02)], .032, "iron", 7)
        mesh.ellipsoid("beacon", (.57, 2.98, .02), (.19, .19, .19), "red", 9, 5)
    return mesh.surface_spec("patchwork-expression-foreman")


def part_specs():
    return {
        "body": {"role": "body", "side": "center", "parent": None, "pivot": [0, .25, 0]},
        "head": {"role": "head", "side": "center", "parent": "body", "pivot": [0, 1.60, 0]},
        "identity_ring": {"role": "identity", "side": "left", "parent": "head", "pivot": [-.31, 2.10, .49], "identity_protected": True},
        "nose": {"role": "identity", "side": "center", "parent": "head", "pivot": [0, 1.91, .58], "identity_protected": True},
        "eye_left": {"role": "eye", "side": "left", "parent": "head", "pivot": [-.31, 2.10, .55]},
        "eye_right": {"role": "eye", "side": "right", "parent": "head", "pivot": [.29, 2.10, .52]},
        "brow_left": {"role": "brow", "side": "left", "parent": "head", "pivot": [-.31, 2.34, .59]},
        "brow_right": {"role": "brow", "side": "right", "parent": "head", "pivot": [.29, 2.34, .59]},
        "mouth": {"role": "mouth", "side": "center", "parent": "head", "pivot": [0, 1.70, .57]},
        "arm_left": {"role": "arm", "side": "left", "parent": "body", "pivot": [-.82, 1.52, 0]},
        "arm_right": {"role": "arm", "side": "right", "parent": "body", "pivot": [.82, 1.52, 0]},
        "leg_left": {"role": "leg", "side": "left", "parent": "body", "pivot": [-.42, .48, 0]},
        "leg_right": {"role": "leg", "side": "right", "parent": "body", "pivot": [.42, .48, 0]},
        "prop": {"role": "prop", "side": "left", "parent": "arm_left", "pivot": [-.99, .45, .16]},
        "backpack": {"role": "detail", "side": "center", "parent": "body", "pivot": [0, 1.25, -.45]},
        "antenna": {"role": "detail", "side": "right", "parent": "head", "pivot": [.42, 2.42, .02]},
    }


def glb_chunks(path):
    body = path.read_bytes()
    magic, version, length = struct.unpack_from("<4sII", body)
    assert (magic, version, length) == (b"glTF", 2, len(body))
    json_length, kind = struct.unpack_from("<II", body, 12)
    assert kind == 0x4E4F534A
    document = json.loads(body[20:20 + json_length])
    offset = 20 + json_length
    binary_length, kind = struct.unpack_from("<II", body, offset)
    assert kind == 0x004E4942
    return body, document, body[offset + 8:offset + 8 + binary_length]


def accessor(document, binary, ref):
    item = document["accessors"][ref]
    view = document["bufferViews"][item["bufferView"]]
    widths, formats = {"SCALAR": 1, "VEC3": 3, "VEC4": 4}, {5123: "H", 5126: "f"}
    width, code = widths[item["type"]], formats[item["componentType"]]
    decoder = struct.Struct("<" + code * width)
    start = view.get("byteOffset", 0) + item.get("byteOffset", 0)
    stride = view.get("byteStride", decoder.size)
    return [decoder.unpack_from(binary, start + index * stride) for index in range(item["count"])]


def add_text(bpy, text, location, size=.16):
    curve = bpy.data.curves.new(text, "FONT")
    curve.body, curve.align_x, curve.align_y = text, "CENTER", "CENTER"
    curve.size, curve.extrude, curve.bevel_depth = size, .008, .003
    obj = bpy.data.objects.new(text, curve)
    bpy.context.scene.collection.objects.link(obj)
    obj.location, obj.rotation_euler = location, (math.pi / 2, 0, 0)
    material = bpy.data.materials.get("Proof captions") or bpy.data.materials.new("Proof captions")
    material.diffuse_color = (.72, .82, .92, 1)
    obj.data.materials.append(material)


def import_variants(bpy, output):
    imported = {}
    for expression, stance in VARIANTS:
        before = set(bpy.data.objects)
        bpy.ops.import_scene.gltf(filepath=str(output / f"{expression}__{stance}.glb"))
        fresh = [obj for obj in bpy.data.objects if obj not in before]
        root = bpy.data.objects.new(f"POSE__{expression}__{stance}", None)
        bpy.context.scene.collection.objects.link(root)
        root.location.x = OFFSETS[expression]
        for obj in fresh:
            if obj.parent is None:
                obj.parent = root
            if obj.type == "MESH":
                obj["axm_expression"], obj["axm_stance"] = expression, stance
        imported[expression] = [obj for obj in fresh if obj.type == "MESH"]
    return imported


def scene_setup(bpy, output):
    from mathutils import Vector
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_EEVEE_NEXT"
    scene.render.resolution_x, scene.render.resolution_y, scene.render.resolution_percentage = 2100, 950, 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.filepath = str(output)
    scene.view_settings.look = "AgX - Medium High Contrast"
    world = bpy.data.worlds.new("Character expression proof world")
    world.color = (.016, .022, .034)
    scene.world = world
    bpy.ops.mesh.primitive_plane_add(size=26, location=(0, 0, -.36))
    floor = bpy.context.object
    floor.name = "PROOF_ONLY_FLOOR"
    floor_material = bpy.data.materials.new("Proof floor")
    floor_material.diffuse_color = (.035, .045, .065, 1)
    floor_material.metallic, floor_material.roughness = .42, .34
    floor.data.materials.append(floor_material)
    bpy.ops.object.camera_add(location=(0, -24.6, 5.1))
    camera = bpy.context.object
    camera.rotation_euler = ((Vector((0, 0, 1.30)) - camera.location).to_track_quat("-Z", "Y").to_euler())
    camera.data.lens = 58
    scene.camera = camera
    for location, power, size, color in [((-6, -5, 8), 1250, 4.5, (1.0, .70, .45)),
                                          ((6, -3, 6), 900, 3.8, (.40, .70, 1.0))]:
        bpy.ops.object.light_add(type="AREA", location=location)
        light = bpy.context.object
        light.data.energy, light.data.shape, light.data.size, light.data.color = power, "DISK", size, color
        light.rotation_euler = ((Vector((0, 0, 1.3)) - light.location).to_track_quat("-Z", "Y").to_euler())
    for expression, stance in VARIANTS:
        add_text(bpy, expression.upper(), (OFFSETS[expression], -.38, 3.52), .17)
        add_text(bpy, stance.replace("-", " ").upper(), (OFFSETS[expression], -.38, 3.25), .10)


def build(output):
    import bpy
    output.mkdir(parents=True, exist_ok=False)
    source, controls = character_mesh(), part_specs()
    packages = {}
    for expression, stance in VARIANTS:
        pose = apply_character_expression(source, controls, expression, stance)
        styled = apply_game_render_style(pose["realization"], "painted-adventure-baked", 471)
        built = build_glb(styled["realization"])
        assert verify_glb(built["body"])["unlit_materials"] == len(styled["realization"]["primitives"])
        name = f"{expression}__{stance}"
        (output / f"{name}.glb").write_bytes(built["body"])
        packages[name] = {"pose": pose, "render": styled,
                          "glb_sha256": hashlib.sha256(built["body"]).hexdigest()}
    (output / "character-expression-packages.json").write_text(json.dumps(packages, indent=2) + "\n")
    bpy.ops.wm.read_factory_settings(use_empty=True)
    import_variants(bpy, output)
    text = bpy.data.texts.new("AXM_CHARACTER_EXPRESSION_PACKAGES.json")
    text.write(json.dumps(packages, indent=2))
    scene_setup(bpy, output / "source.png")
    bpy.ops.wm.save_as_mainfile(filepath=str(output / "character-expression-proof.blend"))
    bpy.ops.render.render(write_still=True)


def verify(output):
    from PIL import Image
    import bpy
    packages = json.loads((output / "character-expression-packages.json").read_text())
    rows, max_position_error = [], 0.0
    for expression, stance in VARIANTS:
        name = f"{expression}__{stance}"
        body, document, binary = glb_chunks(output / f"{name}.glb")
        expected = packages[name]["render"]["realization"]
        for mesh, primitive in zip(document["meshes"], expected["primitives"]):
            actual = accessor(document, binary, mesh["primitives"][0]["attributes"]["POSITION"])
            max_position_error = max(max_position_error, *(abs(actual[row][axis] - primitive["positions"][row][axis])
                                                            for row in range(len(actual)) for axis in range(3)))
        receipt = packages[name]["pose"]["identity_receipt"]
        assert receipt["passed"]
        rows.append({"expression": expression, "stance": stance,
                     "sha256": hashlib.sha256(body).hexdigest(),
                     "primitives": len(document["meshes"]),
                     "triangles": verify_glb(body)["triangles"],
                     "protected_components": receipt["protected_components"],
                     "identity_max_error": max(receipt["maximum_protected_radial_signature_error"],
                                               receipt["maximum_protected_pairwise_pivot_distance_error"],
                                               receipt["maximum_authored_eye_pivot_spacing_error"])})
    assert max_position_error < 1e-6, max_position_error
    bpy.ops.wm.open_mainfile(filepath=str(output / "character-expression-proof.blend"))
    assert "AXM_CHARACTER_EXPRESSION_PACKAGES.json" in bpy.data.texts
    editable_meshes = sum(obj.get("axm_expression") in OFFSETS for obj in bpy.data.objects if obj.type == "MESH")
    bpy.ops.wm.read_factory_settings(use_empty=True)
    imported = import_variants(bpy, output)
    assert all(imported.values())
    scene_setup(bpy, output / "reimport.png")
    bpy.ops.render.render(write_still=True)
    source = Image.open(output / "source.png").convert("RGB").tobytes()
    restored = Image.open(output / "reimport.png").convert("RGB").tobytes()
    mae = sum(abs(a - b) for a, b in zip(source, restored)) / len(source)
    assert mae < 2, mae
    report = {
        "schema": "axm.character-expression-roundtrip/v0.1",
        "blender": bpy.app.version_string,
        "variants": rows,
        "maximum_position_float_error": max_position_error,
        "editable_source_variant_meshes": editable_meshes,
        "source_reimport_render_mae": mae,
        "limits": (
            "Four static expression/stance specimens. No skeleton, clips, deformation, contact, collision, "
            "game-distance, target-engine or performance acceptance."
        ),
    }
    (output / "verification.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("build", "verify"))
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    (build if args.mode == "build" else verify)(args.output.resolve())
