"""Actual layered sticker placement, 1000-instance reuse and animated GLB proof."""
import copy
import hashlib
import json
import math
from pathlib import Path
import shutil
import struct
import sys
import time

sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'src'))
from axm_stickers import Registry,instance
from axm_uc import sticker_adapter as adapter
from axm_uc.fabric_noise import png_bytes
from axm_uc.procedural_3d import build_glb
from axm_uc.game_pose_runtime import GamePoseAsset,_parse

ORIGIN={'author':'AXM','license':'CC0-1.0','source':'Original salvage signal badge, generated by tools/sticker_proof.py'}


def project(width,height,layers,sources=None):
    return {'schema':'axm.studio-composition-project/v1','sources':sources or {},
            'recipe':{'schema':'axm.raster-composition/v1','canvas':{'width':width,'height':height},'layers':layers}}


def frame(t):
    angle=0.65*math.sin(t*math.pi)
    c,s=math.cos(angle),math.sin(angle)
    return [c,-s,0,0.5*math.sin(t*math.pi),s,c,0,0.4*math.sin(t*math.pi),0,0,1,0,0,0,0,1]


def standalone(root):
    repo=Path(__file__).resolve().parents[1]
    package=root/'standalone-core'; package.mkdir()
    shutil.copytree(repo/'src/axm_stickers',package/'axm_stickers',ignore=shutil.ignore_patterns('__pycache__'))
    shutil.copyfile(repo/'LICENSE',package/'LICENSE')
    (package/'pyproject.toml').write_text('''[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
[project]
name = "axm-sticker-fabric"
version = "0.1.0"
description = "Portable offline sticker definitions and registry"
requires-python = ">=3.11"
dependencies = []
[project.scripts]
axm-stickers = "axm_stickers.__main__:main"
[tool.setuptools]
packages = ["axm_stickers"]
''')
    (package/'README.md').write_text('# AXM Sticker Fabric core\n\nInstall with `python -m pip install .`. This package imports only the Python standard library.\nIt registers, searches, bundles and resolves stickers; renderers are external adapters.\nNo UC, Node, AI, network or account is needed for the core.\nThe first UC adapters consume these definitions for Studio layers and rigid GLB attachment.\n')


def build(destination):
    root=Path(destination); root.mkdir(parents=True,exist_ok=False)
    plate,signal=bytearray(),bytearray()
    for y in range(96):
        for x in range(96):
            inside=5<=x<91 and 5<=y<91 and 20<=x+y<=170 and abs(x-y)<73
            rim=inside and (x<11 or x>84 or y<11 or y>84 or x+y<26 or x+y>164 or abs(x-y)>67)
            nick=inside and (x*23+y*17)%131<4
            color=(207,148,41) if rim else ((86,108,127) if nick else (27,42,60))
            plate.extend((*color,255 if inside else 0))
            bolt=(33<=x<53 and 20<=y<43) or (24<=x<67 and 40<=y<52) or (47<=x<62 and 48<=y<75)
            screw=any((x-a)**2+(y-b)**2<8 for a,b in ((18,18),(78,18),(18,78),(78,78)))
            signal.extend((45,237,239,255) if bolt else ((231,212,166,255) if screw else (0,0,0,0)))
    for key,pixels in [('plate',plate),('signal',signal)]: (root/f'{key}.png').write_bytes(png_bytes(96,96,4,bytes(pixels)))
    source=project(96,96,[{'id':'plate','source_artifact_id':'plate'},
        {'id':'signal','source_artifact_id':'signal','opacity':1.0}],{'plate':'plate.png','signal':'signal.png'})
    parameters={'signal-opacity':{'type':'number','min':0,'max':1,'default':1.0,
                                  'path':['project','recipe','layers',1,'opacity']}}
    host=project(420,220,[{'id':'background','fill':'#111C2D'}])
    with Registry(root/'registry.sqlite') as registry:
        d=adapter.register_studio(registry,source,root,id='salvage-signal',name='Salvage signal badge',
                                 anchor=[48,48],parameters=parameters,tags=['salvage','signal'],**ORIGIN)
        placed=[instance(d,'upright',placement={'translation':[78,108]}),
                instance(d,'tilted',placement={'translation':[211,108],'rotation':-22,'scale':[1.25,1.25]}),
                instance(d,'dimmed',overrides={'signal-opacity':0.35},placement={'translation':[341,108],'rotation':16})]
        adapter.publish_sticker_scene(root/'scene',registry,host,root,placed)
        scene=json.loads((root/'scene/scene.json').read_text())
        with Registry(root/'scene/stickers.sqlite') as subset:
            adapter.publish_sticker_scene(root/'scene-replay',subset,scene['host'],root/'scene',scene['instances'])
        assert (root/'scene/preview/composition.png').read_bytes()==(root/'scene-replay/preview/composition.png').read_bytes()
        # Indexed metadata and shared source blobs, not 1000 independent PNG copies.
        start=time.perf_counter()
        for i in range(1000):
            entry=copy.deepcopy(d); entry['id']=f'catalog-fixture-{i}'
            registry.register(entry)
        catalog_seconds=time.perf_counter()-start
        assert registry.db.execute('SELECT count(*) FROM assets').fetchone()[0]==2
        assert len(registry.search(tag='signal',limit=100)['entries'])==100
        many=[instance(d,f'part-{i}',placement={'translation':[8+(i%40)*16,8+(i//40)*16],
                                               'scale':[0.14,0.14]}) for i in range(1000)]
        start=time.perf_counter(); tiled=adapter.stamp_layer(registry,many,width=640,height=400)
        placement_seconds=time.perf_counter()-start
        assert tiled['receipt']['unique_renders']==1
        (root/'thousand-placements.png').write_bytes(tiled['png'])
        primitives=[]
        def box(id,size,position,color,metal=.3):
            primitives.append({'id':id,'type':'box','size':size,'translation':position,
                               'material':{'color':color,'metallic':metal,'roughness':.5}})
        box('outer-plate',[.96,1.06,.12],[0,0,0],'#C48A25',.7)
        box('inset',[.8,.9,.05],[0,0,.08],'#253A50',.5)
        for i,(x,y) in enumerate([(-.34,-.4),(.34,-.4),(-.34,.4),(.34,.4)]):
            box(f'bolt-{i}',[.07,.07,.04],[x,y,.12],'#E4D5AD',.8)
        for i,(x,y,w,h) in enumerate([(-.08,.2,.15,.27),(-.01,.05,.4,.12),(.08,-.12,.13,.27)]):
            box(f'signal-{i}',[w,h,.04],[x,y,.13],'#30E8EF',.1)
        box('crooked-repair',[.18,.06,.03],[.2,-.3,.12],'#AC603E',.6)
        spec={'schema':'axm.procedural-3d/v0.1','name':'Salvage Signal Raised Badge','primitives':primitives}
        original=build_glb(spec)['body']
        three=adapter.register_glb(registry,original,id='raised-signal',name='Raised signal badge',socket='bolt',
                                  editable_source=json.dumps(spec,indent=2).encode(),tags=['salvage','3d'],**ORIGIN)
        motion=[{'time':i/8,'frame':frame(i/8)} for i in range(17)]
        attached=adapter.attach_glb(registry,instance(three,'shoulder-badge'),
                                   {'space':'3d','socket':'bolt','frame':frame(0)},motion=motion)
        (root/'animated-badge.glb').write_bytes(attached['body']); (root/'original-badge.glb').write_bytes(original)
        (root/'editable-badge.json').write_text(json.dumps(spec,indent=2)+'\n')
        asset=GamePoseAsset(attached['body']); maximum=0
        for item in motion:
            pose=asset.sample('StickerSocketMotion',item['time'],vertices=True)
            point=asset.point(pose,attached['receipt']['mount_node'])
            maximum=max(maximum,max(abs(a-b) for a,b in zip(point,[item['frame'][3],item['frame'][7],item['frame'][11]])))
        assert maximum<1e-6
        receipt={'schema':'axm.sticker-proof/v1','two_d_replay_exact':True,'instances':tiled['receipt'],
                 'catalog_fixture_count':1000,'catalog_seconds':catalog_seconds,'placement_seconds':placement_seconds,
                 'registry_bytes':(root/'registry.sqlite').stat().st_size,'source_pngs_shared':True,
                 'glb_socket_max_error_m':maximum,'glb_samples':len(motion),
                 'limits':'Local measured execution only. No target-engine, continuous playback or aesthetic acceptance claim.'}
    standalone(root)
    (root/'proof.json').write_text(json.dumps(receipt,indent=2)+'\n')
    return receipt


def preview(root):
    # Optional offline inspection sheet, built from actual output PNG and GLB poses.
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection
    root=Path(root); body=(root/'animated-badge.glb').read_bytes()
    asset=GamePoseAsset(body); doc,binary=_parse(body)
    def indices(ref):
        a=doc['accessors'][ref]; v=doc['bufferViews'][a['bufferView']]
        fmt={5123:'H',5125:'I'}[a['componentType']]
        return struct.unpack_from('<'+fmt*a['count'],binary,v.get('byteOffset',0)+a.get('byteOffset',0))
    fig=plt.figure(figsize=(12,7),facecolor='#101929')
    top=fig.add_subplot(2,1,1); top.imshow(plt.imread(root/'scene/preview/composition.png')); top.axis('off')
    top.set_title('ONE EDITABLE STICKER / THREE INDEPENDENT INSTANCES',color='white',fontsize=13)
    for slot,t in enumerate([0,.5,1.5],1):
        ax=fig.add_subplot(2,3,slot+3,projection='3d')
        pose=asset.sample('StickerSocketMotion',t,vertices=True)
        all_triangles,all_colors=[],[]
        for mesh in pose['meshes']:
            primitive=doc['meshes'][doc['nodes'][mesh['node']]['mesh']]['primitives'][mesh['primitive']]
            ids=indices(primitive['indices']); vertices=mesh['positions']
            triangles=[[vertices[i] for i in ids[j:j+3]] for j in range(0,len(ids),3)]
            color=doc['materials'][primitive.get('material',0)]['pbrMetallicRoughness']['baseColorFactor']
            all_triangles.extend(triangles); all_colors.extend([color]*len(triangles))
        ax.add_collection3d(Poly3DCollection(all_triangles,facecolors=all_colors,edgecolors='#182331',linewidths=.25))
        ax.set(xlim=(-1.3,1.3),ylim=(-1.3,1.3),zlim=(-.5,.7))
        ax.view_init(elev=67,azim=-65); ax.set_box_aspect((1,1,.5)); ax.set_axis_off(); ax.set_facecolor('#101929')
        ax.set_title(f'EXPORTED SOCKET POSE / {t:.1f}s',color='white',fontsize=11)
    fig.text(.5,.02,'Actual GLB geometry • offline flat-colour inspection • editable source retained',ha='center',color='#AFBFCE')
    fig.tight_layout(rect=(0,.04,1,1)); fig.savefig(root/'sticker-proof.png',dpi=150,facecolor=fig.get_facecolor()); plt.close(fig)


if __name__=='__main__':
    if sys.argv[1]=='preview': preview(sys.argv[2])
    else: print(json.dumps(build(sys.argv[1]),indent=2))
